const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {ChannelCache}=require('./channel-cache'),{createSync}=require('./ns-sync');
const cache=()=>new ChannelCache(fs.mkdtempSync(path.join(os.tmpdir(),'cacife-cache-test-')));
test('persisted data is immediately available after restart without calling the provider',async()=>{const c=cache();await c.put('test',{value:7});const reloaded=new ChannelCache(c.directory);let calls=0;const d=await reloaded.get('test',async()=>{calls++;return {value:8};});assert.equal(d.value,7);assert.equal(calls,0);assert.equal(d.cache.refreshing,false);});
test('stale data remains available during a single background refresh and on failure',async()=>{const c=cache();await c.put('test',{value:7},Date.now()-5000);let release,calls=0;const load=()=>{calls++;return new Promise(resolve=>{release=resolve;});};const [a,b]=await Promise.all([c.get('test',load,{ttl:1000}),c.get('test',load,{ttl:1000})]);assert.equal(a.value,7);assert.equal(b.cache.refreshing,true);assert.equal(calls,1);release({value:8});await c.pending.get('test');assert.equal((await c.get('test',load)).value,8);await c.get('test',async()=>{throw Error('Provider offline');},{force:true});await c.pending.get('test').catch(()=>{});const failed=await c.get('test',load);assert.equal(failed.value,8);assert.equal(failed.cache.error,'Provider offline');});
test('a wider ML period can serve a shorter period without querying again',async()=>{const c=cache();await c.put('ml-orders:2026-09-01:2026-09-30',{orders:[]});assert(c.coveringOrders('2026-09-10','2026-09-15'));assert.equal(c.coveringOrders('2026-08-31','2026-09-15'),undefined);});
test('Nuvemshop reuses its index across periods and merges updates without duplicates',async()=>{const c=cache(),calls=[];let release,authCalls=0;const initial={id:'1',created:'2026-09-15T12:00:00Z',paidAt:'2026-09-15T12:00:00Z',payment:'paid'};const sync=createSync(c,{auth:async()=>authCalls++,scan:async(options,since)=>{calls.push(since);if(calls.length===1)return [initial];return new Promise(resolve=>{release=resolve;});}});const first=await sync.orders({},'2026-09-01','2026-09-16');assert.equal(first.orders.length,1);const narrow=await sync.orders({},'2026-09-15','2026-09-15');assert.equal(narrow.orders.length,1);assert.equal(calls.length,1);const old=await sync.orders({},'2026-09-15','2026-09-15',true);assert.equal(old.cache.refreshing,true);assert(new Date(calls[1])>new Date('2026-09-01'));release([{...initial,payment:'refunded'}]);await new Promise(resolve=>setTimeout(resolve,30));const updated=await sync.orders({},'2026-09-15','2026-09-15');assert.equal(updated.orders.length,1);assert.equal(updated.orders[0].payment,'refunded');assert.equal(authCalls,4);});
test('Nuvemshop authenticates before returning a cached index',async()=>{const c=cache();await c.put('ns-order-index',{coverageStart:'2026-09-01',syncedAt:new Date().toISOString(),orders:[]});const sync=createSync(c,{auth:async()=>{throw Error('Denied');},scan:async()=>{throw Error('Should not scan');}});await assert.rejects(sync.orders({},'2026-09-01','2026-09-16'),/Denied/);});

test('annual Nuvemshop index includes older paid orders and reuses history for narrower ranges',async()=>{const c=cache();let calls=0;const sync=createSync(c,{auth:async()=>{},scan:async()=>{calls++;return [{id:'old',created:'2024-01-01T12:00:00Z',paidAt:'2026-01-01T12:00:00Z'},{id:'end',created:'2026-09-16T12:00:00Z',paidAt:'2026-09-16T12:00:00Z'},{id:'outside',created:'2024-01-01T12:00:00Z',paidAt:'2024-01-01T12:00:00Z'}];}});const all=await sync.orders({},'2025-09-16','2026-09-16');assert.deepEqual(all.orders.map(o=>o.id).sort(),['end','old']);assert.equal((await sync.orders({},'2026-01-01','2026-01-01')).orders[0].id,'old');assert.equal(calls,1);await assert.rejects(sync.orders({},'2025-09-15','2026-09-16'),/366/);});
