const test=require('node:test'),assert=require('node:assert/strict');
const W=require('./ns-workspace'),C=require('../ns-core');
const raw={id:1,store_id:1081093,number:100,created_at:'2026-08-01T10:00:00-03:00',paid_at:'2026-09-15T10:00:00-03:00',status:'open',payment_status:'paid',currency:'BRL',total:'100.00',subtotal:'120.00',discount:'20.00',products:[],contact_email:'private'};
test('Nuvemshop excludes personal data, enforces store, and preserves payment dates',()=>{const o=W.cleanOrder(raw);assert(!JSON.stringify(o).includes('private'));assert.equal(o.total,10000);assert.equal(o.paidAt,raw.paid_at);assert.throws(()=>W.cleanOrder({...raw,store_id:22}),/fora/);});
test('sales use paid_at even for older orders and never substitute creation for missing dates',()=>{const rows=[W.cleanOrder(raw),W.cleanOrder({...raw,id:2,created_at:raw.paid_at,paid_at:null}),W.cleanOrder({...raw,id:3,payment_status:'refunded'}),W.cleanOrder({...raw,id:4,status:'cancelled'})];const s=C.summarize(rows,'2026-09-15','2026-09-15');assert.equal(s.revenue,10000);assert.equal(s.paid,1);assert.equal(s.missingDate,1);assert.equal(s.byDay['2026-09-15'],10000);assert.throws(()=>C.summarize([rows[0],rows[0]],'2026-09-15','2026-09-15'),/duplicado/);});
test('unmanaged stock and missing values are not zero, unsafe images removed',()=>{const p=W.cleanProduct({id:1,name:{pt:'Óculos'},images:[{src:'https://evil.example/image'}],variants:[{id:1,stock_management:false,stock:null},{id:2,stock_management:true,stock:0}]});assert.equal(p.image,null);assert.equal(p.variants[0].stock,null);assert.equal(p.variants[0].managed,false);assert.equal(p.variants[1].stock,0);});
test('order scan uses updates to include older orders paid in period and sanitizes before returning',async()=>{let queried;const options={serviceKey:'k',authorization:'Bearer test',config:{storeId:1081093,token:'private'},fetchImpl:async url=>{if(url.includes('/auth/'))return {ok:true,json:async()=>({id:'9d41b952-5345-4bb9-bac2-ee64023d88bd'})};queried=new URL(url);return {ok:true,headers:new Headers(),json:async()=>[raw]};}};const d=await W.orders(options,'2026-09-15','2026-09-15');assert.equal(d.orders.length,1);assert(queried.searchParams.has('updated_at_min'));assert(!queried.searchParams.has('created_at_min'));});
test('pagination never forwards the private credential outside the fixed store',async()=>{let calls=0;const options={serviceKey:'k',authorization:'Bearer test',config:{storeId:1081093,token:'private'},fetchImpl:async url=>{calls++;if(url.includes('/auth/'))return {ok:true,json:async()=>({id:'9d41b952-5345-4bb9-bac2-ee64023d88bd'})};return {ok:true,headers:new Headers({link:'<https://evil.example/steal>; rel="next"'}),json:async()=>[]};}};await assert.rejects(W.products(options),/fora/);assert.equal(calls,2);});
test('small order pages preserve creation snapshot through complete pagination',async()=>{
 const urls=[];const options={serviceKey:'k',authorization:'Bearer test',config:{storeId:1081093,token:'private'},fetchImpl:async url=>{if(url.includes('/auth/'))return {ok:true,json:async()=>({id:'9d41b952-5345-4bb9-bac2-ee64023d88bd'})};const u=new URL(url);urls.push(u);const page=Number(u.searchParams.get('page')||1);const next=new URL(u);next.searchParams.set('page','2');return {ok:true,headers:new Headers({'x-total-count':'2',...(page===1?{link:'<'+next.href+'>; rel="next", <'+next.href+'>; rel="last"'}:{})}),json:async()=>[{...raw,id:page}]};}};
 const data=await W.orders(options,'2026-09-15','2026-09-15');assert.equal(data.orders.length,2);assert.equal(urls.length,2);assert(urls.every(u=>u.searchParams.get('per_page')==='30'));assert.equal(urls[0].searchParams.get('created_at_max'),urls[1].searchParams.get('created_at_max'));assert(urls[0].searchParams.get('created_at_max'));
});
test('real API quantity strings become numeric and shipped orders appear in operations',()=>{const o=W.cleanOrder({...raw,created_at:raw.paid_at,shipping_status:'shipped',products:[{product_id:1,quantity:'2',price:'50.00'}]});const s=C.summarize([o],'2026-09-15','2026-09-15');assert.equal(s.operations.fulfilled,1);assert.equal(s.ranking[0].units,2);assert.equal(s.ranking[0].value,10000);});

test('large Nuvemshop searches split update ranges before reaching the 10000 order limit',async()=>{
 const queries=[];const options={serviceKey:'k',authorization:'Bearer test',config:{storeId:1081093,token:'private'},fetchImpl:async url=>{
 if(url.includes('/auth/'))return {ok:true,json:async()=>({id:'9d41b952-5345-4bb9-bac2-ee64023d88bd'})};
 const q=new URL(url).searchParams;queries.push(q);const first=queries.length===1;
 return {ok:true,headers:new Headers({'x-total-count':first?'25000':'1'}),json:async()=>[{...raw,id:7}]};
 }};
 const rows=await W.changedOrders(options,'2026-01-01T00:00:00Z','2026-09-17T00:00:00Z');
 assert.equal(queries.length,3);assert.equal(rows.length,1);assert.equal(queries[1].get('updated_at_max'),queries[2].get('updated_at_min'));
 assert.equal(queries[1].get('updated_at_min'),'2026-01-01T00:00:00Z');assert.equal(queries[2].get('updated_at_max'),'2026-09-17T00:00:00Z');
 assert(queries.every(q=>q.get('per_page')==='30'&&!q.has('page')));
});

test('Nuvemshop retries a temporary server failure on the same page',async()=>{let calls=0;const options={serviceKey:'k',authorization:'Bearer test',config:{storeId:1081093,token:'private'},fetchImpl:async url=>{if(url.includes('/auth/'))return {ok:true,json:async()=>({id:'9d41b952-5345-4bb9-bac2-ee64023d88bd'})};calls++;return {ok:calls>1,status:calls===1?503:200,headers:new Headers(),json:async()=>[raw]};}};const result=await W.orders(options,'2026-09-15','2026-09-15');assert.equal(calls,2);assert.equal(result.orders.length,1);});
