document.addEventListener('DOMContentLoaded',async()=>{
 'use strict';
 const M=window.CacifeMetrics,C=window.MLCore,$=id=>document.getElementById(id);
 const n=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
 const money=v=>Number.isFinite(v)?(v/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'Não informado';
 const num=v=>Number.isFinite(v)?v.toLocaleString('pt-BR'):'—';
 const date=v=>v&&Number.isFinite(new Date(v).getTime())?new Date(v).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'short',timeStyle:'short'}):'Não informado';
 const shortDate=v=>v.split('-').reverse().join('/');
 const names={loading:'Consultando',no_shipment:'Sem envio informado',unavailable:'Consulta indisponível',master:'Mastercard',visa:'Visa',elo:'Elo',amex:'American Express',consumer_credits:'Crédito Mercado Pago',bolbradesco:'Boleto',in_mediation:'Em mediação',partially_refunded:'Reembolso parcial',in_progress:'A caminho ou a enviar',no_tags:'Clique em Atualizar',paid:'Pago',cancelled:'Cancelado',confirmed:'Confirmado',payment_required:'Aguardando pagamento',payment_in_process:'Pagamento em análise',partially_paid:'Parcialmente pago',approved:'Aprovado',pending:'Pendente',in_process:'Em análise',rejected:'Recusado',refunded:'Reembolsado',charged_back:'Estornado',handling:'Em preparação',ready_to_ship:'Pronto para envio',shipped:'Em transporte',delivered:'Entregue',not_delivered:'Não entregue',returned:'Devolvido',active:'Ativo',paused:'Pausado',closed:'Encerrado',UNANSWERED:'Sem resposta',ANSWERED:'Respondida',fulfillment:'Full',cross_docking:'Coleta',xd_drop_off:'Ponto de envio',self_service:'Flex',drop_off:'Agência',gold_special:'Clássico',gold_pro:'Premium',credit_card:'Cartão de crédito',debit_card:'Cartão de débito',bank_transfer:'Transferência',account_money:'Saldo Mercado Pago',pix:'Pix'};
 const label=v=>names[v]||v||'Não informado';
 const badge=v=>n('span','badge '+(['paid','approved','delivered','active','ANSWERED'].includes(v)?'good':['cancelled','rejected','charged_back','not_delivered'].includes(v)?'bad':['pending','in_process','UNANSWERED'].includes(v)?'warn':''),label(v));
 const button=(text,fn,cls='')=>{const b=n('button',cls,text);b.type='button';b.addEventListener('click',fn);return b;};
 const panel=(title,caption)=>{const e=n('section','card');const head=n('div','card-head');head.append(n('h2','',title));e.append(head);if(caption)e.append(n('p','caption',caption));return e;};
 const empty=(target,text)=>target.append(n('p','empty',text));
 let pollTimer,lastRange='';const resource={orders:{},previous:{},summary:{}};let client,tab='resumo',epoch=0,view=0,orderPage=0,paymentPage=0,listingPage=0,questionPage=0,listingStatus='active',questionStatus='UNANSWERED',listingQuery='',questionsData,selectedQuestion,drafts=new Map();
 const shipments=new Map();let csrfPromise;const elapsed=v=>{const hours=Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/3600000));return hours<1?'Há menos de 1 hora':hours<24?'Há '+hours+' horas':'Há '+Math.floor(hours/24)+' dias';};const titles={resumo:'Resumo',pedidos:'Pedidos e entregas',produtos:'Produtos',anuncios:'Anúncios',pagamentos:'Pagamentos',perguntas:'Perguntas'};
 const today=M.day(new Date());$('end').value=today;$('start').value=M.shift(today,-29);
 const params=new URLSearchParams(location.search);if(params.get('start')&&params.get('end')){try{M.range(params.get('start'),params.get('end'));$('start').value=params.get('start');$('end').value=params.get('end');}catch{}}
 async function request(route,query={}){const {data:{session}}=await client.auth.getSession();if(!session){location.href='login.html';throw Error('Entre novamente.');}const key=session.user.id+':mercadolivre:'+route+':'+new URLSearchParams(query);return window.CacifeFastData.get(key,()=>networkRequest(route,query),query.refresh==='1');}
 async function networkRequest(route,query={},retried=false){const {data:{session}}=await client.auth.getSession();if(!session){location.href='login.html';throw Error('Entre novamente.');}if(!csrfPromise)csrfPromise=fetch('/api/session').then(async r=>{if(!r.ok)throw Error('Servidor local indisponível.');return r.json();}).catch(e=>{csrfPromise=null;throw e;});const {csrf}=await csrfPromise;const r=await fetch('/api/channels/mercadolivre'+route+(Object.keys(query).length?'?'+new URLSearchParams(query):''),{headers:{Authorization:'Bearer '+session.access_token,'X-Cacife-Local':csrf}});if(r.status===403){csrfPromise=null;if(!retried)return networkRequest(route,query,true);throw Error('Sessão local expirada. Clique em Atualizar.');}const d=await r.json();if(!r.ok)throw Error(d.error||'Consulta indisponível.');return d;}
 function product(title,subtitle,image){const box=n('div','product');if(image){const img=n('img');img.src=image;img.alt='';img.loading='lazy';img.referrerPolicy='no-referrer';img.addEventListener('error',()=>img.replaceWith(n('span','product-placeholder','◉')),{once:true});box.append(img);}else box.append(n('span','product-placeholder','◉'));const copy=n('div');copy.append(n('strong','',title||'Produto'));if(subtitle)copy.append(n('small','',subtitle));box.append(copy);return box;}
 function link(text,url){if(!url)return n('span','muted','Link indisponível');const a=n('a','',text);a.href=url;a.target='_blank';a.rel='noopener noreferrer';return a;}
 function table(target,headers,rows){const wrap=n('div','table-wrap'),t=n('table'),head=n('thead'),tr=n('tr');headers.forEach(x=>tr.append(n('th','',x)));head.append(tr);t.append(head);const body=n('tbody');rows.forEach(row=>{const tr=n('tr');row.forEach(value=>{const td=n('td');if(value instanceof Node)td.append(value);else td.textContent=value??'Não informado';tr.append(td);});body.append(tr);});t.append(body);wrap.append(t);target.append(wrap);if(!rows.length)empty(target,'Nenhum registro encontrado com estes filtros.');}
 function pager(target,total,page,size,change){const e=n('div','pager');e.append(n('span','',total===null?'Total não informado':`${num(total)} registros · página ${page+1} de ${Math.max(1,Math.ceil(total/size))}`));const controls=n('div');const prev=button('← Anterior',()=>change(page-1)),next=button('Próxima →',()=>change(page+1));prev.disabled=page===0;next.disabled=total===null||((page+1)*size>=total);controls.append(prev,next);e.append(controls);target.append(e);}
 function searchBar(placeholder,onSearch,options=[]){const form=n('form','toolbar');const field=n('label','search','Buscar');const input=n('input');input.type='search';input.placeholder=placeholder;field.append(input);form.append(field);const selects=[];for(const [title,values]of options){const field=n('label','',title),select=n('select');for(const [value,text]of values){const opt=n('option','',text);opt.value=value;select.append(opt);}field.append(select);form.append(field);selects.push(select);}form.append(button('Filtrar',()=>onSearch(input.value.trim(),...selects.map(s=>s.value))));form.addEventListener('submit',e=>{e.preventDefault();onSearch(input.value.trim(),...selects.map(s=>s.value));});selects.forEach(s=>s.addEventListener('change',()=>onSearch(input.value.trim(),...selects.map(s=>s.value))));return {form,input,selects};}
 function failure(target,error,retry){target.replaceChildren(n('p','error',error));if(retry)target.append(button('Tentar novamente',retry));}
 function drawChart(target,entries,previous=[],bars=false){
  if(!entries.length){empty(target,'Sem dados para o gráfico.');return;}
  const NS='http://www.w3.org/2000/svg',wrap=n('div','interactive-chart'),tooltip=n('div','chart-tooltip'),svg=document.createElementNS(NS,'svg');tooltip.hidden=true;tooltip.setAttribute('role','status');tooltip.setAttribute('aria-live','polite');svg.setAttribute('viewBox','0 0 620 240');svg.setAttribute('class','chart');svg.setAttribute('role','group');svg.setAttribute('aria-label',bars?'Visitas diárias. Passe o mouse, toque ou use Tab para ver detalhes.':'Vendas diárias. Passe o mouse, toque ou use Tab para ver detalhes.');
  const add=(tag,attrs,text)=>{const e=document.createElementNS(NS,tag);for(const [k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;svg.append(e);return e;};
  const max=Math.max(1,...entries.map(x=>x[1]),...previous.map(x=>x[1]));for(let i=0;i<5;i++){const y=15+i*46;add('line',{x1:58,x2:600,y1:y,y2:y,stroke:'#eef0f3'});add('text',{x:50,y:y+4,'text-anchor':'end'},bars?num(Math.round(max*(1-i/4))):'R$ '+Math.round(max*(1-i/4)/100).toLocaleString('pt-BR'));}
  const x=i=>70+i*520/Math.max(1,entries.length-1),y=v=>199-v/max*184;
  const line=(rows,color,dash)=>{const e=add('polyline',{points:rows.map((d,i)=>x(i)+','+y(d[1])).join(' '),fill:'none',stroke:color,'stroke-width':2.5});if(dash)e.setAttribute('stroke-dasharray','6 6');};if(previous.length)line(previous,'#9ca3af',true);
  if(bars)entries.forEach((d,i)=>add('rect',{x:x(i)-Math.min(10,200/entries.length),y:y(d[1]),width:Math.min(20,400/entries.length),height:199-y(d[1]),rx:3,fill:'#f2c200'}));else{line(entries,'#3483fa');entries.forEach((d,i)=>add('circle',{cx:x(i),cy:y(d[1]),r:3,fill:'#3483fa'}));}
  for(const i of [...new Set([0,Math.floor((entries.length-1)/2),entries.length-1])])add('text',{x:x(i),y:224,'text-anchor':'middle'},entries[i][0].slice(5).split('-').reverse().join('/'));
  const guide=add('line',{x1:70,x2:70,y1:12,y2:200,stroke:'#3483fa','stroke-width':1,'stroke-dasharray':'3 3',visibility:'hidden'});
  function show(i){const d=entries[i];tooltip.replaceChildren(n('strong','',shortDate(d[0].slice(0,10))),n('div','',(bars?'Visitas: ':'Vendas: ')+(bars?num(d[1]):money(d[1]))));if(!bars&&previous[i]){const p=previous[i];tooltip.append(n('div','',shortDate(p[0].slice(0,10))+' · anterior: '+money(p[1])));if(p[1])tooltip.append(n('small','',(d[1]>=p[1]?'↑ ':'↓ ')+Math.abs((d[1]/p[1]-1)*100).toLocaleString('pt-BR',{maximumFractionDigits:1})+'%'));}tooltip.hidden=false;guide.setAttribute('x1',x(i));guide.setAttribute('x2',x(i));guide.setAttribute('visibility','visible');const width=wrap.clientWidth,position=x(i)/620*width;tooltip.style.left=Math.max(8,Math.min(width-tooltip.offsetWidth-8,position-tooltip.offsetWidth/2))+'px';}
  function hide(){tooltip.hidden=true;guide.setAttribute('visibility','hidden');}
  entries.forEach((d,i)=>{const step=520/Math.max(1,entries.length-1),left=entries.length===1?58:Math.max(58,x(i)-step/2),right=entries.length===1?602:Math.min(602,x(i)+step/2);const hit=add('rect',{x:left,y:5,width:right-left,height:202,fill:'transparent',tabindex:0,role:'button','aria-label':shortDate(d[0].slice(0,10))+': '+(bars?num(d[1])+' visitas':money(d[1]))+(!bars&&previous[i]?'; anterior '+money(previous[i][1]):'')});hit.addEventListener('pointerenter',()=>show(i));hit.addEventListener('pointermove',()=>show(i));hit.addEventListener('click',()=>show(i));hit.addEventListener('focus',()=>show(i));hit.addEventListener('blur',hide);hit.addEventListener('keydown',event=>{if(event.key==='Escape')hide();if(event.key==='Enter'||event.key===' '){event.preventDefault();show(i);}});});wrap.addEventListener('pointerleave',hide);wrap.append(svg,tooltip);target.append(wrap);
 }

 function dataState(key,paint){const r=resource[key];if(r.error){failure($('content'),r.error,loadPeriod);return false;}if(!r.data){$('content').append(n('div','loading',key==='orders'?'Consultando todos os pedidos do período…':'Consultando dados…'));return false;}paint(r.data);return true;}
 // Variação vs. período anterior (texto + se é bom/ruim). inverse=true quando subir é ruim (comissão, cancelados).
 function compare(cur,prev,inverse=false){if(resource.previous.error)return {text:'Comparação indisponível',cls:''};if(!prev)return {text:'Consultando período anterior…',cls:''};if(!prev[1])return {text:'Sem base anterior',cls:''};const pct=(cur/prev[1]-1)*100,up=pct>=0;return {text:(up?'▲ ':'▼ ')+Math.abs(pct).toLocaleString('pt-BR',{maximumFractionDigits:1})+'%',cls:(up!==inverse)?'up':'down'};}
 function kpiCard(title,icon,value,cmp){const c=n('div','ml-kpi');const h=n('div','ml-kpi-head'),ic=n('span','ml-kpi-icon');ic.setAttribute('aria-hidden','true');ic.append(n('i','ph '+icon));h.append(ic,n('span','',title),n('i','ml-kpi-bar'));const d=n('div','ml-kpi-delta');d.append(n('span',cmp.cls,cmp.text));if(cmp.cls)d.append(n('small','',' vs. anterior'));c.append(h,n('strong','',value),d);return c;}
 // Nome curto para listas (até ~30 letras, cortando na palavra); o nome completo fica no título (passar o mouse).
 function shortName(t){t=String(t||'Produto').replace(/\s+/g,' ').trim();if(t.length<=30)return t;const cut=t.slice(0,30);return cut.slice(0,Math.max(cut.lastIndexOf(' '),18)).replace(/[\s,.;:–-]+$/,'')+'…';}
 function overview(){const target=$('content');let s,p;try{s=resource.orders.data?C.summarize(resource.orders.data.orders):null;p=resource.previous.data?C.summarize(resource.previous.data.orders):null;}catch(e){failure(target,e.message);return;}
  const block=n('section','card ml-block'),four=n('div','ml-four');
  for(const [text,key,icon,fmt,inv]of [['Vendas confirmadas','revenue','ph-currency-circle-dollar',money,false],['Comissão Mercado Livre','fees','ph-percent',money,true],['Pedidos pagos','paid','ph-bag-simple',num,false],['Unidades vendidas','units','ph-package',num,false]]){
   const cmp=!s?{text:resource.orders.error?'Consulta indisponível':'Consultando pedidos…',cls:''}:compare(s[key],p?[0,p[key]]:null,inv);four.append(kpiCard(text,icon,s?fmt(s[key]):'—',cmp));}
  const dark=n('div','ml-dark');const dh=n('div','ml-dark-head'),logo=n('span','platform-icon channel-emblem mercadolivre');logo.setAttribute('aria-hidden','true');const li=n('img');li.src='mercadolivre-logo.png';li.alt='';logo.append(li);dh.append(logo,n('span','','Repasse líquido'));
  const netCmp=!s?{text:'',cls:''}:compare(s.net,p?[0,p.net]:null);const nd=n('div','ml-dark-main');nd.append(n('small','','O que sobra depois das comissões do Mercado Livre'),n('strong','',s?money(s.net):'—'),n('span','ml-dark-delta '+netCmp.cls,netCmp.text+(netCmp.cls?' vs. período anterior':'')));
  const foot=n('div','ml-dark-foot');foot.append(n('small','','do valor bruto'),n('strong','',s&&s.revenue>0?(s.net/s.revenue*100).toLocaleString('pt-BR',{maximumFractionDigits:1})+'%':'—'));
  dark.append(dh,nd,foot);block.append(four,dark);target.append(block);
  if(resource.orders.error)target.append(n('p','error',resource.orders.error));if(resource.previous.error)target.append(n('p','caption','Comparação: '+resource.previous.error));
  const grid=n('div','grid ml-row2'),sales=panel('Evolução das vendas','Pedidos criados no período · situação atual. Valores brutos, sem deduzir reembolsos parciais.'),health=panel('Saúde da conta','Posição atual informada pelo Mercado Livre.'),visits=panel('Visitas aos anúncios','Janela de 30 dias informada pelo Mercado Livre.');
  if(s){const entries=[],prev=[];const count=Math.round((new Date($('end').value)-new Date($('start').value))/86400000)+1;for(let i=0;i<count;i++){const day=M.shift($('start').value,i);entries.push([day,s.byDay[day]||0]);if(p){const before=M.shift($('start').value,i-count);prev.push([before,p.byDay[before]||0]);}}sales.append(n('div','chart-summary',money(s.revenue)),n('p','caption',shortDate($('start').value)+' a '+shortDate($('end').value)));const legend=n('div','chart-legend');legend.innerHTML='<span><i></i>Período atual</span><span><i class="previous"></i>Período anterior</span>';if(p)sales.append(legend);drawChart(sales,entries,prev);}else empty(sales,resource.orders.error?'Vendas indisponíveis.':'Carregando vendas…');
  const info=resource.summary.data;
  if(info){const levels={'5_green':['Verde','#00a650'],'4_light_green':['Verde-claro','#86efac'],'3_yellow':['Amarela','#facc15'],'2_orange':['Laranja','#f97316'],'1_red':['Vermelha','#e5484d']};const lv=levels[info.reputation?.level];const rep=n('span','reputation','Reputação '+(lv?lv[0]:'não informada'));if(!['5_green','4_light_green'].includes(info.reputation?.level))rep.classList.add('warn');health.querySelector('.card-head').append(rep);
   const thermo=n('div','ml-thermo');for(const k of ['1_red','2_orange','3_yellow','4_light_green','5_green']){const i=n('i');i.style.background=levels[k][1];if(k===info.reputation?.level)i.className='on';thermo.append(i);}health.append(thermo);
   const rows=n('div','ml-kv');for(const [key,title]of [['claims','Reclamações'],['delayed_handling_time','Atrasos de preparação'],['cancellations','Cancelamentos do vendedor']]){const m=info.reputation?.metrics?.[key],r=n('div');r.append(n('span','',title),n('strong','',Number.isFinite(m?.rate)?(m.rate*100).toLocaleString('pt-BR',{maximumFractionDigits:2})+'%':'—'));r.title=num(m?.value)+' ocorrências · '+String(m?.period||'Período não informado').replace('days','dias');rows.append(r);}
   for(const [title,value]of [['Anúncios ativos',info.activeListings],['Anúncios pausados',info.pausedListings]]){const r=n('div');r.append(n('span','',title),n('strong','',num(value)));rows.append(r);}
   const q=n('div');const qs=n('strong','',num(info.unansweredQuestions));if(info.unansweredQuestions>0)qs.classList.add('alert');const go=button('Ver perguntas →',()=>{location.hash='perguntas';},'link-button');const right=n('span','ml-kv-right');right.append(qs,go);q.append(n('span','','Perguntas sem resposta'),right);rows.append(q);health.append(rows);}
  else empty(health,resource.summary.error||'Consultando reputação…');
  if(info?.visits){visits.append(n('div','chart-summary',num(info.visits.total)),n('p','caption',shortDate(info.visits.from.slice(0,10))+' a '+shortDate(info.visits.to.slice(0,10))));drawChart(visits,info.visits.days.map(d=>[d.date.slice(0,10),d.total]).sort((a,b)=>a[0].localeCompare(b[0])),[],true);}else empty(visits,resource.summary.error||'Consultando visitas…');
  grid.append(sales,visits);
  const top=panel('Produtos mais vendidos','Top 5 do período por unidades de pedidos pagos.');
  if(s){const rows=s.ranking.slice(0,5);if(!rows.length)empty(top,'Nenhum produto vendido no período.');const list=n('div','ml-top');rows.forEach((i,k)=>{const row=n('div','ml-top-row');row.title=i.title||'';row.append(n('span','ml-top-rank',String(k+1)),product(shortName(i.title),num(i.quantity)+' un'+(i.variation?' · variação '+i.variation:''),resource.orders.data.products?.find(p=>p.id===i.id)?.image),n('strong','',money(i.value)));list.append(row);});top.append(list);const more=button('Ver todos os produtos →',()=>{location.hash='produtos';},'link-button');more.style.marginTop='10px';top.append(more);}else empty(top,resource.orders.error||'Consultando itens dos pedidos…');
  const methods=panel('Métodos de pagamento','Pagamentos do período por método, do mais usado para o menos usado.');if(resource.orders.data){const mc={};for(const {payment:pm}of C.paymentRows(resource.orders.data.orders)){if(!Object.keys(pm).length)continue;const k=pm.method||pm.type||'Não informado';mc[k]=(mc[k]||0)+1;}const pie=n('div','pie-layout');methods.append(pie);drawPie(pie,mc,'Métodos de pagamento','pagamentos');}else empty(methods,resource.orders.error||'Consultando pagamentos…');
  const grid2=n('div','grid ml-row-pm');grid2.append(top,methods);health.classList.add('ml-health-wide');target.append(grid,grid2,health);
 }
 async function openOrder(order,mode='order'){const dlg=$('detail'),body=$('detail-content');body.replaceChildren(n('h2','',`Pedido #${order.id}`),n('p','caption','Criado em '+date(order.created)),badge(order.status));const items=panel(mode==='payment'?'Comissões informadas por item':'Produtos');table(items,['Produto','Quantidade','Preço unitário',...(mode==='payment'?['Comissão por item']:[])],order.items.map(i=>[product(i.title,(i.sku?'SKU '+i.sku:'SKU não informado')+(i.variation?' · Variação '+i.variation:'')),num(i.quantity),money(i.price),...(mode==='payment'?[money(i.fee)]:[])]));body.append(items);const totals=n('div','detail-totals');totals.append(n('span','','Total do pedido'),n('strong','',money(order.total)),n('span','','Valor pago informado'),n('strong','',money(order.paid)));body.append(totals);if(mode==='payment'){body.append(n('p','caption','Comissão informada por item, sem total consolidado. Não representa lucro ou repasse.'));table(body,['Pagamento','Método','Parcelas','Aprovado em','Reembolsado'],order.payments.map(p=>[badge(p.status),label(p.method||p.type),p.installments?`${p.installments}x`:'Não informado',date(p.approved),money(p.refunded)]));}else{const area=panel('Rastreamento e histórico');area.append(n('p','loading','Consultando envio…'));body.append(area);getShipment(order.id).then(s=>{if(!body.contains(area))return;area.replaceChildren(n('h2','','Rastreamento e histórico'));if(!s){empty(area,'Pedido sem envio informado.');return;}area.append(n('p','caption',label(s.logistics)+' · '+label(s.status)),n('p','','Rastreamento: '+(s.tracking||'Não informado')));const ul=n('ul','timeline');for(const [key,title]of [['date_handling','Preparação'],['date_ready_to_ship','Pronto para envio'],['date_shipped','Enviado'],['date_delivered','Entregue'],['estimate','Entrega prevista']]){const li=n('li');li.append(n('strong','',title),n('small','',date(key==='estimate'?s.estimate:s.history[key])));ul.append(li);}area.append(ul);}).catch(e=>failure(area,e.message));}if(!dlg.open)dlg.showModal();}
 function getShipment(id){if(!shipments.has(id)){const p=request('/workspace/shipment/'+id).then(d=>d.shipment).catch(e=>{shipments.delete(id);throw e;});shipments.set(id,p);}return shipments.get(id);}
 function drawPie(target,counts,title,unit="pedidos"){target.replaceChildren();const entries=Object.entries(counts).filter(([,v])=>v>0).sort((x,y)=>y[1]-x[1]),total=entries.reduce((s,[,v])=>s+v,0);if(!total){empty(target,'Nenhum registro para este gráfico.');return;}const palette={in_progress:'#3483fa',no_tags:'#d1d5db',paid:'#00a650',cancelled:'#b42318',partially_refunded:'#d97706',handling:'#f2c200',ready_to_ship:'#3483fa',shipped:'#2d3277',delivered:'#00a650',pending:'#92620c',loading:'#d7d0df',unavailable:'#756582',no_shipment:'#aaa0b8',not_delivered:'#b42318',returned:'#92620c'};const colors=entries.map(([key])=>palette[key]||['#3483fa','#f2c200','#00a650','#2d3277','#f97316','#0891b2','#a16207','#475569'][entries.findIndex(([k])=>k===key)%8]);let position=0;const stops=entries.map(([,value],i)=>{const from=position;position+=value/total*100;return colors[i%colors.length]+' '+from+'% '+position+'%';});const chart=n('div','pie-disc');chart.style.background='conic-gradient('+stops.join(',')+')';chart.setAttribute('role','img');chart.setAttribute('aria-label',title+': '+entries.map(([key,value])=>label(key)+' '+num(value)).join(', '));const center=n('div','pie-center');center.append(n('strong','',num(total)),n('small','',unit));chart.append(center);const legend=n('div','pie-legend');entries.forEach(([key,value],i)=>{const row=n('div'),dot=n('i');dot.style.backgroundColor=colors[i%colors.length];row.append(dot,n('span','',label(key)),n('strong','',num(value)+' · '+(value/total*100).toLocaleString('pt-BR',{maximumFractionDigits:2})+'%'));legend.append(row);});target.append(chart,legend);}
 // ---------- Pedidos e Pagamentos no desenho do TikTok Shop (channel-kit.js), cores do ML ----------
 const ML_KIT={accent:'#2d3277',accent2:'#3483fa',bar:'#ffe600'};
 // mesmas cores das pizzas de antes (Entregues/Pago = verde #00a650)
 const ML_PAL={in_progress:'#3483fa',no_tags:'#d1d5db',paid:'#00a650',cancelled:'#b42318',partially_refunded:'#d97706',handling:'#f2c200',ready_to_ship:'#3483fa',shipped:'#2d3277',delivered:'#00a650',pending:'#92620c',loading:'#d7d0df',unavailable:'#756582',no_shipment:'#aaa0b8',not_delivered:'#b42318',returned:'#92620c',approved:'#00a650',refunded:'#d97706',rejected:'#b42318',charged_back:'#b42318',in_process:'#f2c200',in_mediation:'#d97706'};
 const ML_EXTRA=['#3483fa','#f2c200','#00a650','#2d3277','#f97316','#0891b2','#a16207','#475569'];
 const pieEntries=counts=>{const e=Object.entries(counts).filter(([,v])=>v>0).sort((x,y)=>y[1]-x[1]);return e.map(([k,v],i)=>[label(k),v,ML_PAL[k]||ML_EXTRA[i%8]]);};
 const toneOf=v=>['paid','approved','delivered','active','ANSWERED'].includes(v)?'g':['cancelled','rejected','charged_back','not_delivered'].includes(v)?'rd':['pending','in_process','UNANSWERED','partially_refunded','in_mediation','handling','ready_to_ship','refunded'].includes(v)?'am':v==='shipped'?'cy':'gy';
 const mlImage=id=>{for(const p of [...(resource.orders.data?.products||[]),...(resource.previous.data?.products||[])])if(p&&p.id===id&&p.image)return p.image;return mlThumbs.get(id)||null;};
 const mlOrderState={},mlPayState={};
 function orderView(orders){const K=window.ChannelKit;if(!K){failure($('content'),'Não foi possível carregar os pedidos.');return;}const H=K.h;let shipSummary=null,pies=null;
  const cnt={};for(const o of orders)cnt[o.status]=(cnt[o.status]||0)+1;
  const groups=[{key:'',label:'Todos',color:'#2d3277'},...Object.keys(cnt).sort((a,b)=>cnt[b]-cnt[a]).map(s=>({key:s,label:label(s),color:ML_PAL[s]||'#9ca3af',red:s==='cancelled'}))];
  const drawShipping=(arr)=>{if(!pies)return;const hasTags=arr.some(o=>Array.isArray(o.tags));const sc={};for(const o of arr){const t=o.tags||[];const k=!hasTags?'no_tags':o.status==='cancelled'?'cancelled':t.includes('delivered')?'delivered':t.includes('not_delivered')?'not_delivered':'in_progress';sc[k]=(sc[k]||0)+1;}pies.ship.innerHTML=K.donutBlock(pieEntries(sc),'pedidos');if(!shipSummary)shipSummary=request('/workspace/shipping-summary',{start:$('start').value,end:$('end').value}).catch(()=>null);shipSummary.then(d=>{if(d&&d.counts&&pies.ship.isConnected)pies.ship.innerHTML=K.donutBlock(pieEntries(d.counts),'pedidos');});};
  let run=0;
  K.ordersView($('content'),{...ML_KIT,state:mlOrderState,groups,groupOf:o=>o.status,rows:orders,title:'Pedidos e entregas',caption:'Pedidos criados no período · abra um pedido para ver o rastreamento e o histórico',search:'Número do pedido ou produto',text:o=>o.id+' '+o.items.map(i=>i.title).join(' '),
   above:node=>{node.className='ck-grid ck-cols';node.style.cssText='grid-template-columns:minmax(0,1fr) minmax(0,1fr);margin-bottom:16px';node.innerHTML=`<div class="ck-card">${H.chead('Situação dos pedidos','Todos os pedidos do período, respeitando os filtros abaixo')}<div class="ck-fill ml-pie-st"></div></div><div class="ck-card">${H.chead('Andamento das entregas','Todos os pedidos do período, pela situação de entrega informada pelo Mercado Livre')}<div class="ck-fill ml-pie-sh"></div></div>`;pies={st:node.querySelector('.ml-pie-st'),ship:node.querySelector('.ml-pie-sh')};},
   onFilter:arr=>{if(!pies)return;const sc={};for(const o of arr)sc[o.status]=(sc[o.status]||0)+1;pies.st.innerHTML=K.donutBlock(pieEntries(sc),'pedidos');drawShipping(arr);},
   columns:[{h:'Pedido',cls:'nw',cell:(o,i)=>H.openBtn('#'+o.id,i)},{h:'Criado em',cls:'nw',cell:o=>H.esc(H.when(o.created))},
    {h:'Produto',cell:o=>{const it=o.items[0]||{},q=o.items.reduce((t,x)=>t+(x.quantity||0),0);return `<span class="ck-pn">${H.foto(mlImage(it.id))}${H.pname(it.title||'Produto',230,H.esc(q+' un.'+(o.items.length>1?' · '+o.items.length+' anúncios':'')))}</span>`;}},
    {h:'Valor',cls:'r',cell:o=>`<b>${H.esc(money(o.total))}</b>`},{h:'Pedido',cls:'nw',cell:o=>H.pill(label(o.status),toneOf(o.status))},
    {h:'Envio',cls:'nw',cell:()=>'<span class="ck-mut ml-ship">Consultando…</span>'},{h:'Logística',cls:'nw',cell:()=>'<span class="ck-mut ml-log">—</span>'},{h:'Previsão',cls:'nw',cell:()=>'<span class="ck-mut ml-est">—</span>'}],
   onOpen:o=>openOrder(o),
   afterPaint:(rows,trs)=>{const my=++run;let idx=0;Promise.all(Array.from({length:3},async()=>{while(idx<rows.length){const i=idx++,o=rows[i],tr=trs[i];if(!tr)continue;const sh=tr.querySelector('.ml-ship'),lg=tr.querySelector('.ml-log'),es=tr.querySelector('.ml-est');try{const s=await getShipment(o.id);if(my!==run||!tr.isConnected)return;if(s){sh.outerHTML=H.pill(label(s.status),toneOf(s.status));lg.textContent=label(s.logistics);es.textContent=H.when(s.estimate);}else sh.textContent='Sem envio';}catch{if(my!==run)return;sh.textContent='Indisponível';}}}));
    const need=rows.map(o=>o.items[0]?.id).filter(id=>id&&!mlImage(id)&&!mlThumbs.has(id));if(need.length)loadThumbs(need).then(m=>{if(Object.keys(m).length&&$('content').isConnected&&tab==='pedidos')trs.forEach((tr,i)=>{const u=m[rows[i]?.items[0]?.id];const ph=tr.querySelector('.ck-foto');if(u&&ph&&ph.tagName!=='IMG'){ph.outerHTML=H.foto(u);}});});}});
 }
 function paymentsView(orders){const K=window.ChannelKit;if(!K){failure($('content'),'Não foi possível carregar os pagamentos.');return;}const H=K.h;
  let s,p=null;try{s=C.summarize(orders);if(resource.previous.data)p=C.summarize(resource.previous.data.orders);}catch(e){failure($('content'),e.message);return;}
  const prev=f=>resource.previous.data?(p?f(p):0):(resource.previous.error?0:undefined);
  const rows=C.paymentRows(orders),refundOf=list=>C.paymentRows(list).reduce((t,{payment:x})=>t+(Number.isSafeInteger(x.refunded)?x.refunded:0),0);
  const refunded=refundOf(orders),prevRefunded=resource.previous.data?refundOf(resource.previous.data.orders):prev(()=>0);
  // pedidos que contam como venda (mesmo critério do Resumo), por método e por dia de aprovação
  const sold=new Set(C.itemRows(orders).map(r=>r.orderId));const byMethod={},byDay={};
  for(const o of orders){if(!sold.has(o.id))continue;const ap=(o.payments||[]).find(x=>x.status==='approved')||o.payments?.[0]||{};const m=ap.method||ap.type||'Não informado';const g=byMethod[m]||(byMethod[m]={n:0,v:0,parc:0});g.n++;g.v+=o.total||0;if(ap.installments>1)g.parc++;const d=ap.approved?K.toDay(ap.approved):'';if(d)byDay[d]=(byDay[d]||0)+(o.total||0);}
  const dates=K.dayList($('start').value,$('end').value);
  const methods=Object.entries(byMethod).sort((a,b)=>b[1].v-a[1].v);
  const stCnt={};for(const r of rows){const k=r.payment.status||'none';stCnt[k]=(stCnt[k]||0)+1;}
  const groups=[{key:'',label:'Todos'},...Object.keys(stCnt).sort((a,b)=>stCnt[b]-stCnt[a]).map(k=>({key:k,label:k==='none'?'Sem pagamento':label(k)}))];
  K.financeView($('content'),{...ML_KIT,logo:'mercadolivre-logo.png',
   hero:{title:'Repasse líquido',value:s.net,sub:H.delta(s.net,prev(x=>x.net)).replace('vs. anterior','vs. período anterior'),foot:H.esc('Vendas − comissões do Mercado Livre · '+(s.revenue>0?(s.net/s.revenue*100).toLocaleString('pt-BR',{maximumFractionDigits:1})+'% do bruto':'—'))},
   kpis:[['Vendas confirmadas','ph-currency-circle-dollar',H.esc(money(s.revenue)),H.delta(s.revenue,prev(x=>x.revenue)),{money:true}],['Comissão Mercado Livre','ph-percent',H.esc(money(s.fees)),H.delta(s.fees,prev(x=>x.fees),true)],['Reembolsado','ph-arrow-u-up-left',H.esc(money(refunded)),H.delta(refunded,prevRefunded,true)]],
   waterfall:{title:'Das vendas ao repasse',caption:'Pedidos pagos no período · comissões informadas por item · o custo de frete não vem nesta consulta',steps:[['Vendas',s.revenue,'t'],['Comissão ML',-s.fees],['Repasse',s.net,'t']]},
   side:{title:'Por método de pagamento',caption:'Pedidos pagos no período, pelo método do pagamento aprovado',rows:methods.map(([m,g],i)=>({label:label(m),sub:g.parc?num(g.parc)+' parcelados':'',n:num(g.n)+' pedidos',value:g.v,color:ML_EXTRA[i%8]})),total:{label:'Total vendido',value:s.revenue}},
   bars:{title:'Vendas aprovadas por dia',caption:'Valor dos pedidos pagos pela data de aprovação do pagamento',dates,vals:dates.map(d=>byDay[d]||0),name:'Aprovado',empty:'Sem aprovações'},
   list:{state:mlPayState,tiles:false,groups,groupOf:r=>r.payment.status||'none',rows,title:'Pagamentos e comissões',caption:'Cada linha é um pagamento · período pela criação do pedido',search:'Número do pedido ou produto',text:r=>r.order.id+' '+r.order.items.map(i=>i.title).join(' '),pageSize:15,
    selects:[{label:'Método',options:[['','Todos os métodos'],...Array.from(new Set(rows.map(r=>r.payment.method).filter(Boolean))).map(v=>[v,label(v)])],test:(r,v)=>r.payment.method===v}],
    columns:[{h:'Pedido',cls:'nw',cell:(r,i)=>H.openBtn('#'+r.order.id,i)},{h:'Situação',cls:'nw',cell:r=>r.payment.status?H.pill(label(r.payment.status),toneOf(r.payment.status)):H.pill('Sem pagamento','gy')},{h:'Método',cls:'nw',cell:r=>H.esc(label(r.payment.method||r.payment.type))},{h:'Parcelas',cls:'r',cell:r=>r.payment.installments?H.esc(r.payment.installments+'x'):'—'},{h:'Aprovado em',cls:'nw',cell:r=>H.esc(H.when(r.payment.approved))},{h:'Total do pedido',cls:'r',cell:r=>`<b>${H.esc(money(r.order.total))}</b>`},{h:'Reembolsado',cls:'r',cell:r=>r.payment.refunded>0?`<span class="ck-red">− ${H.esc(money(r.payment.refunded))}</span>`:'<span class="ck-mut">—</span>'},{h:'',cls:'r',cell:(r,i)=>H.openBtn('Ver comissões →',i)}],
    onOpen:r=>openOrder(r.order,'payment'),
    csv:{name:'mercado-livre-pagamentos-'+$('start').value+'.csv',rows:list=>[['Pedido','Criado em','Situação','Método','Parcelas','Aprovado em','Total do pedido','Reembolsado'],...list.map(({order:o,payment:x})=>[o.id,o.created,label(x.status),label(x.method||x.type),x.installments||'',x.approved||'',H.csvMoney(o.total),H.csvMoney(x.refunded)])]}}});
 }
 // Aba Produtos: mesmo desenho do TikTok Shop (channel-kit.js), nas cores do ML. Fotos que não vierem com os pedidos são buscadas aos poucos.
 const mlThumbs=new Map();
 async function loadThumbs(ids){const out={},need=ids.filter(id=>/^MLB\d+$/.test(id)&&!mlThumbs.has(id));for(let i=0;i<need.length;i+=20){const chunk=need.slice(i,i+20);try{const d=await request('/workspace/thumbnails',{ids:chunk.join(',')});for(const id of chunk)mlThumbs.set(id,(d.images||{})[id]||'');}catch{}}for(const id of ids)if(mlThumbs.get(id))out[id]=mlThumbs.get(id);return out;}
 function productsView(){const target=$('content'),K=window.ChannelKit,kit={accent:'#2d3277',accent2:'#3483fa',bar:'#ffe600'};if(!K){failure(target,'Não foi possível carregar os produtos.');return;}if(!resource.orders.data){K.message(target,resource.orders.error||'Consultando itens dos pedidos…',kit);return;}
  let rows,prevRows=null;try{rows=C.itemRows(resource.orders.data.orders);if(resource.previous.data)prevRows=C.itemRows(resource.previous.data.orders);}catch(e){failure(target,e.message);return;}
  const imgs=new Map();for(const p of [...(resource.orders.data.products||[]),...(resource.previous.data?.products||[])])if(p&&p.id&&p.image&&!imgs.has(p.id))imgs.set(p.id,p.image);for(const [id,u]of mlThumbs)if(u&&!imgs.has(id))imgs.set(id,u);
  for(const r of rows)r.image=imgs.get(r.id)||null;
  K.productsView(target,{...kit,rows,prevRows,prevLoading:!resource.previous.data&&!resource.previous.error,start:$('start').value,end:$('end').value,loadImages:loadThumbs});
 }
 function listingsView(){const list=panel('Anúncios e estoque informado','Preços e estoque: posição atual · Vendidos acumulados: histórico do anúncio.');$('content').append(list);const content=n('div');const controls=searchBar('Produto ou identificador do anúncio',(q,status)=>{listingQuery=q;listingStatus=status;listingPage=0;load();},[['Situação',[['active','Ativos'],['paused','Pausados'],['closed','Encerrados']]]]);controls.input.value=listingQuery;controls.selects[0].value=listingStatus;list.append(controls.form,content);const stamp=view;let counter=0;async function load(){const id=++counter;content.replaceChildren(n('p','loading','Consultando anúncios e preços…'));try{const d=await request('/workspace/listings',{status:listingStatus,offset:listingPage*20,q:listingQuery});if(stamp!==view||id!==counter)return;content.replaceChildren();table(content,['Produto','Situação','Preço atual','Qtd. disponível','Vendidos acumulados','Tipo','Logística',''],d.items.map(i=>{const stock=n('div');stock.append(n('span','',num(i.stock)));if(i.stock!==null&&i.stock<=5)stock.append(n('div','badge warn',i.stock<=0?'Sem estoque':'Estoque baixo'));return [product(i.title,i.id,i.image),badge(i.status),money(i.price),stock,num(i.sold),label(i.type),label(i.logistics),link('Ver anúncio ↗',i.url)];}));content.append(n('p','caption','Alerta de estoque baixo: até 5 unidades informadas pela plataforma.'));pager(content,d.total,listingPage,20,p=>{listingPage=p;load();});}catch(e){if(stamp===view&&id===counter)failure(content,e.message,load);}}load();}
 // Perguntas no desenho do Atendimento do TikTok Shop: lista | pergunta e resposta | anúncio.
 function questionsView(){questionsData=null;const K=window.ChannelKit;if(!K){failure($('content'),'Não foi possível carregar as perguntas.');return;}const H=K.h,stamp=view;
  const itemOf=q=>questionsData?.products.find(i=>i.id===q.itemId);
  const pagerNode=()=>{const total=questionsData?.total,pages=total==null?null:Math.max(1,Math.ceil(total/20));const d=n('div');d.style.cssText='display:flex;justify-content:space-between;align-items:center;gap:8px;font-size:12px;color:#6b7280';d.append(n('span','',total==null?'Página '+(questionPage+1):num(total)+' perguntas · página '+(questionPage+1)+' de '+pages));const b=n('div');b.style.cssText='display:flex;gap:10px';const prev=button('← Anterior',()=>{questionPage--;selectedQuestion=null;chat.ckChat.reload();},'ck-link'),next=button('Próxima →',()=>{questionPage++;selectedQuestion=null;chat.ckChat.reload();},'ck-link');prev.disabled=questionPage===0;next.disabled=total==null||(questionPage+1)*20>=total;b.append(prev,next);d.append(b);return d;};
  const chat=K.chatView($('content'),{...ML_KIT,side:true,search:'Buscar pergunta ou produto',selected:selectedQuestion,emptyText:questionStatus==='UNANSWERED'?'Nenhuma pergunta sem resposta.':'Nenhuma pergunta respondida.',
   chips:[{key:'UNANSWERED',label:'Sem resposta'},{key:'ANSWERED',label:'Respondidas'}],chip:questionStatus,
   onChip:(k,api)=>{questionStatus=k;questionPage=0;selectedQuestion=null;api.reload();},
   load:async()=>{const d=await request('/workspace/questions',{status:questionStatus,offset:questionPage*20});if(stamp!==view)return [];questionsData=d;chat?.ckChat?.footer(pagerNode());
    return d.questions.map(q=>{const it=itemOf(q);return {id:q.id,q,name:it?.title||q.itemId,image:it?.image||null,time:H.when(q.created).slice(0,5),preview:q.text,search:q.itemId,unread:0};});},
   open:(c,ui)=>{const q=c.q,it=itemOf(q);selectedQuestion=q.id;
    ui.head(it?.title||q.itemId,{image:it?.image},H.pill(label(q.status),q.status==='UNANSWERED'?'am':'g'));
    const msgs=[{side:'c',tag:'Pergunta do comprador',text:q.text,time:date(q.created)}];if(q.answer)msgs.push({side:'s',tag:'Resposta publicada',text:q.answer.text||'Texto não disponível',time:date(q.answer.created)});ui.messages(msgs);
    if(!q.answer)ui.composer({note:'Sua resposta ficará pública no anúncio. Envio em validação · o texto fica só nesta sessão.',disabled:true,draft:{get:()=>drafts.get(q.id),set:v=>drafts.set(q.id,v)}});
    const url=H.safeUrl(it?.url);
    ui.side(`<div style="display:flex;flex-direction:column;gap:10px">${H.foto(it?.image,'big',it?.title||'')}<b title="${H.esc(it?.title||'')}">${H.esc(it?.title||q.itemId)}</b>${url?`<a href="${H.esc(url)}" target="_blank" rel="noopener noreferrer">Ver anúncio ↗</a>`:'<span class="ck-mut">Link indisponível</span>'}</div><h4>Pergunta</h4><div class="ck-kv"><span class="ck-mut">Situação</span>${H.pill(label(q.status),q.status==='UNANSWERED'?'am':'g')}</div><div class="ck-kv"><span class="ck-mut">Recebida em</span><b>${H.esc(date(q.created))}</b></div>${q.status==='UNANSWERED'?`<div class="ck-kv"><span class="ck-mut">Aguardando</span><b>${H.esc(elapsed(q.created))}</b></div>`:''}${q.answer?`<div class="ck-kv"><span class="ck-mut">Respondida em</span><b>${H.esc(date(q.answer.created))}</b></div>`:''}<div class="ck-kv"><span class="ck-mut">Anúncio</span><b>${H.esc(q.itemId)}</b></div>${it?`<div class="ck-kv"><span class="ck-mut">Estoque</span><b>${H.esc(num(it.stock))}</b></div><div class="ck-kv"><span class="ck-mut">Preço</span><b>${H.esc(money(it.price))}</b></div>`:''}<p class="ck-cap" style="margin-top:12px">Posição atual · inclui perguntas fora do período de vendas.</p>`);}});
 }
 function rememberControls(){const forms=[...document.querySelectorAll('#content .toolbar')],active=document.activeElement;const saved=forms.map(form=>[...form.querySelectorAll('input,select')].map(e=>({value:e.value,focused:e===active})));return ()=>{document.querySelectorAll('#content .toolbar').forEach((form,i)=>{const fields=[...form.querySelectorAll('input,select')];saved[i]?.forEach((v,j)=>{if(fields[j])fields[j].value=v.value;});if(saved[i])form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));saved[i]?.forEach((v,j)=>{if(v.focused&&fields[j])fields[j].focus({preventScroll:true});});});};}
 function render(preserve=false){const restore=preserve?rememberControls():null;view++;$('content').replaceChildren();$('content').className='';document.querySelectorAll('[data-tab]').forEach(a=>{if(a.dataset.tab===tab)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});document.title=titles[tab]+' · Mercado Livre | Provou Levou';if(tab==='resumo')overview();else if(tab==='pedidos')dataState('orders',d=>orderView(d.orders));else if(tab==='pagamentos')dataState('orders',d=>paymentsView(d.orders));else if(tab==='produtos')productsView();else if(tab==='anuncios')listingsView();else questionsView();if(restore)restore();updateStatus();}
 function updateStatus(){$('export').disabled=!resource.orders.data;const updating=Object.values(resource).some(r=>r.data?.cache?.refreshing),cacheError=Object.values(resource).find(r=>r.data?.cache?.error)?.data.cache.error;$('updated').textContent=resource.orders.data?'Pedidos consultados em '+date(resource.orders.data.queriedAt)+' · API Mercado Livre'+(updating?' · Atualizando em segundo plano…':cacheError?' · Últimos dados salvos. '+cacheError:' · Dados salvos localmente.'):'Os recursos são consultados separadamente. Dados ausentes não equivalem a zero.';}

 async function loadPeriod(force=false){clearTimeout(pollTimer);let range;try{range=M.range($('start').value,$('end').value);if((new Date($('end').value)-new Date($('start').value))/86400000>365)throw Error('Selecione até 366 dias.');}catch(e){failure($('content'),e.message);return;}const run=++epoch,start=$('start').value,end=$('end').value;const sameRange=lastRange===start+':'+end;lastRange=start+':'+end;if(!sameRange){orderPage=paymentPage=0;mlOrderState.page=mlPayState.page=1;resource.orders={};resource.previous={};if(!resource.summary.data)resource.summary={};}$('date-label').textContent=shortDate(start)+' – '+shortDate(end);$('date-menu').open=false;$('period-note').textContent='Pedidos por data de criação · Brasília'+(end===M.day(new Date())?' · Hoje em andamento':'');for(const b of $('presets').children){const v=b.dataset.period,t=M.day(new Date()),e=v==='yesterday'?M.shift(t,-1):t,s=['today','yesterday'].includes(v)?e:M.shift(t,1-Number(v));b.setAttribute('aria-pressed',String(start===s&&end===e));}const url=new URL(location.href);url.search=new URLSearchParams({start,end});history.replaceState(null,'',url);if(!sameRange)render();else updateStatus();const tasks=[['orders','/workspace/orders',{start,end}],['previous','/workspace/orders',{start:range.previous.slice(0,10),end:M.shift(start,-1)}],['summary','',{}]].filter(([key])=>force!=='poll'||resource[key].data?.cache?.refreshing);await Promise.allSettled(tasks.map(async([key,route,q])=>{let changed=false;try{const data=await request(route,{...q,...(force===true?{refresh:'1'}:{})});if(run!==epoch)return;changed=resource[key].data?.queriedAt!==data.queriedAt;resource[key]={data};}catch(e){if(run!==epoch)return;if(resource[key].data){resource[key].data.cache={...resource[key].data.cache,error:e.message,refreshing:false};}else{resource[key]={error:e.message};changed=true;}}if(run===epoch){if(changed&&(tab==='resumo'||key==='orders'&&['pedidos','pagamentos','produtos'].includes(tab)||key==='previous'&&['produtos','pagamentos'].includes(tab)))render(sameRange);else updateStatus();}}));if(run===epoch&&Object.values(resource).some(r=>r.data?.cache?.refreshing))pollTimer=setTimeout(()=>loadPeriod('poll'),2000);}
 for(const [value,title]of [['today','Hoje'],['yesterday','Ontem'],['7','7 dias'],['15','15 dias'],['30','30 dias']]){const b=button(title,()=>{const t=M.day(new Date());$('end').value=value==='yesterday'?M.shift(t,-1):t;$('start').value=['today','yesterday'].includes(value)?$('end').value:M.shift(t,1-Number(value));loadPeriod();});b.dataset.period=value;$('presets').append(b);}
 $('date-form').addEventListener('submit',e=>{e.preventDefault();loadPeriod();});$('refresh').addEventListener('click',()=>{shipments.clear();loadPeriod(true);});$('close-detail').addEventListener('click',()=>$('detail').close());window.addEventListener('hashchange',()=>{tab=titles[location.hash.slice(1)]?location.hash.slice(1):'resumo';render();});
 $('export').addEventListener('click',()=>{if(!resource.orders.data)return;const rows=[['Pedido','Criado em','Situação','Total BRL','Pago BRL'],...resource.orders.data.orders.map(o=>[o.id,o.created,label(o.status),o.total==null?'':(o.total/100).toFixed(2),o.paid==null?'':(o.paid/100).toFixed(2)])];const csv='\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=n('a');a.href=url;a.download='mercado-livre-pedidos-'+$('start').value+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 try{client=window.supabase.createClient(window.SUPABASE_CONFIG.URL,window.SUPABASE_CONFIG.KEY);const {data:{session}}=await client.auth.getSession();if(!session){location.href='login.html';return;}$('logout').addEventListener('click',async()=>{await client.auth.signOut();location.href='login.html';});tab=titles[location.hash.slice(1)]?location.hash.slice(1):'resumo';await loadPeriod();setInterval(()=>{if(!document.hidden&&!document.querySelector('input:focus,select:focus,textarea:focus'))loadPeriod();},60000);}catch(e){failure($('content'),'Não foi possível iniciar o painel. '+e.message);}
});
