document.addEventListener('DOMContentLoaded',async()=>{
 'use strict';
 const M=window.CacifeMetrics,C=window.NSCore,$=id=>document.getElementById(id);
  const n=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
 const money=v=>Number.isFinite(v)?(v/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'Não informado';
 const num=v=>Number.isFinite(v)?v.toLocaleString('pt-BR'):'—';
 const date=v=>v&&Number.isFinite(new Date(v).getTime())?new Date(v).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'short',timeStyle:'short'}):'Não informado';
 const shortDate=v=>v.split('-').reverse().join('/');
 const button=(text,fn,cls='')=>{const b=n('button',cls,text);b.type='button';b.addEventListener('click',fn);return b;};
 const panel=(title,caption)=>{const e=n('section','card');const head=n('div','card-head');head.append(n('h2','',title));e.append(head);if(caption)e.append(n('p','caption',caption));return e;};
 const empty=(target,text)=>target.append(n('p','empty',text));
 function product(title,subtitle,image){const box=n('div','product');if(image){const img=n('img');img.src=image;img.alt='';img.loading='lazy';img.referrerPolicy='no-referrer';img.addEventListener('error',()=>img.replaceWith(n('span','product-placeholder','◉')),{once:true});box.append(img);}else box.append(n('span','product-placeholder','◉'));const copy=n('div');copy.append(n('strong','',title||'Produto'));if(subtitle)copy.append(n('small','',subtitle));box.append(copy);return box;}
 function table(target,headers,rows){const wrap=n('div','table-wrap'),t=n('table'),head=n('thead'),tr=n('tr');headers.forEach(x=>tr.append(n('th','',x)));head.append(tr);t.append(head);const body=n('tbody');rows.forEach(row=>{const tr=n('tr');row.forEach(value=>{const td=n('td');if(value instanceof Node)td.append(value);else td.textContent=value??'Não informado';tr.append(td);});body.append(tr);});t.append(body);wrap.append(t);target.append(wrap);if(!rows.length)empty(target,'Nenhum registro encontrado com estes filtros.');}
 function pager(target,total,page,size,change){const e=n('div','pager');e.append(n('span','',total===null?'Total não informado':`${num(total)} registros · página ${page+1} de ${Math.max(1,Math.ceil(total/size))}`));const controls=n('div');const prev=button('← Anterior',()=>change(page-1)),next=button('Próxima →',()=>change(page+1));prev.disabled=page===0;next.disabled=total===null||((page+1)*size>=total);controls.append(prev,next);e.append(controls);target.append(e);}
 function searchBar(placeholder,onSearch,options=[]){const form=n('form','toolbar');const field=n('label','search','Buscar');const input=n('input');input.type='search';input.placeholder=placeholder;field.append(input);form.append(field);const selects=[];for(const [title,values]of options){const field=n('label','',title),select=n('select');for(const [value,text]of values){const opt=n('option','',text);opt.value=value;select.append(opt);}field.append(select);form.append(field);selects.push(select);}form.append(button('Filtrar',()=>onSearch(input.value.trim(),...selects.map(s=>s.value))));form.addEventListener('submit',e=>{e.preventDefault();onSearch(input.value.trim(),...selects.map(s=>s.value));});selects.forEach(s=>s.addEventListener('change',()=>onSearch(input.value.trim(),...selects.map(s=>s.value))));return {form,input,selects};}
 function failure(target,error,retry){target.replaceChildren(n('p','error',error));if(retry)target.append(button('Tentar novamente',retry));}
 function drawChart(target,entries,previous=[],bars=false){if(!entries.length){empty(target,'Sem dados para o gráfico.');return;}const NS='http://www.w3.org/2000/svg',svg=document.createElementNS(NS,'svg');svg.setAttribute('viewBox','0 0 620 240');svg.setAttribute('class','chart');svg.setAttribute('role','img');svg.setAttribute('aria-label',bars?'Visitas diárias':'Vendas diárias em reais');const add=(tag,attrs,text)=>{const e=document.createElementNS(NS,tag);for(const [k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;svg.append(e);return e;};const max=Math.max(1,...entries.map(x=>x[1]),...previous.map(x=>x[1]));for(let i=0;i<5;i++){const y=15+i*46;add('line',{x1:58,x2:600,y1:y,y2:y,stroke:'#eee8f5'});add('text',{x:50,y:y+4,'text-anchor':'end'},bars?num(Math.round(max*(1-i/4))):'R$ '+Math.round(max*(1-i/4)/100).toLocaleString('pt-BR'));}const x=i=>70+i*520/Math.max(1,entries.length-1),y=v=>199-v/max*184;const render=(rows,color,dash)=>{const line=add('polyline',{points:rows.map((d,i)=>`${x(i)},${y(d[1])}`).join(' '),fill:'none',stroke:color,'stroke-width':2.5});if(dash)line.setAttribute('stroke-dasharray','6 6');};if(previous.length)render(previous,'#c4a5ff',true);if(bars)entries.forEach((d,i)=>{const rect=add('rect',{x:x(i)-Math.min(10,200/entries.length),y:y(d[1]),width:Math.min(20,400/entries.length),height:199-y(d[1]),rx:3,fill:'#9b6aef'});const title=document.createElementNS(NS,'title');title.textContent=d[0]+': '+num(d[1]);rect.append(title);});else{render(entries,'#7c3aed');entries.forEach((d,i)=>{const circle=add('circle',{cx:x(i),cy:y(d[1]),r:3,fill:'#7c3aed'});const title=document.createElementNS(NS,'title');title.textContent=d[0]+': '+money(d[1]);circle.append(title);});}for(const i of [...new Set([0,Math.floor((entries.length-1)/2),entries.length-1])])add('text',{x:x(i),y:224,'text-anchor':'middle'},entries[i][0].slice(5).split('-').reverse().join('/'));target.append(svg);}
 const names={wallet:'Carteira digital',mobile:'Celular',shipped:'Enviado',delivered:'Entregue',not_delivered:'Não entregue',other:'Outro',custom:'Personalizado',paid:'Pago',pending:'Pendente',authorized:'Autorizado',partially_paid:'Parcialmente pago',refunded:'Reembolsado',partially_refunded:'Reembolso parcial',voided:'Anulado',abandoned:'Abandonado',open:'Aberto',closed:'Fechado',cancelled:'Cancelado',unpacked:'A preparar',unfulfilled:'A enviar',fulfilled:'Enviado',store:'Loja virtual',meli:'Mercado Livre',api:'Integração',form:'Manual',pos:'Ponto de venda',pix:'Pix',credit_card:'Cartão de crédito',debit_card:'Cartão de débito',boleto:'Boleto',bank_transfer:'Transferência',wire_transfer:'Transferência',cash:'Dinheiro'};
 const label=v=>names[v]||v||'Não informado';
 const badge=v=>n('span','badge '+(['paid','fulfilled'].includes(v)?'good':['cancelled','voided'].includes(v)?'bad':v==='pending'?'warn':''),label(v));
 const resource={orders:{},products:{},checkouts:{}};let client,csrfPromise,epoch=0,tab='resumo',pollTimer,lastRange='';
 const titles={resumo:'Resumo',pedidos:'Pedidos',produtos:'Produtos e estoque',pagamentos:'Pagamentos',carrinhos:'Carrinhos abandonados'};
 const today=M.day(new Date());$('end').value=today;$('start').value=M.shift(today,-29);
 const params=new URLSearchParams(location.search);if(params.get('start')&&params.get('end')){try{M.range(params.get('start'),params.get('end'));$('start').value=params.get('start');$('end').value=params.get('end');}catch{}}
 async function request(route,query={}){const {data:{session}}=await client.auth.getSession();if(!session){location.href='login.html';throw Error('Entre novamente.');}const key=session.user.id+':nuvemshop:'+route+':'+new URLSearchParams(query);return window.CacifeFastData.get(key,()=>networkRequest(route,query),query.refresh==='1');}
 async function networkRequest(route,query={},retried=false){const {data:{session}}=await client.auth.getSession();if(!session){location.href='login.html';throw Error('Entre novamente.');}if(!csrfPromise)csrfPromise=fetch('/api/session').then(async r=>{if(!r.ok)throw Error('Servidor local indisponível.');return r.json();}).catch(e=>{csrfPromise=null;throw e;});const {csrf}=await csrfPromise;const r=await fetch('/api/channels/nuvemshop/workspace/'+route+'?'+new URLSearchParams(query),{headers:{Authorization:'Bearer '+session.access_token,'X-Cacife-Local':csrf}});if(r.status===403){csrfPromise=null;if(!retried)return networkRequest(route,query,true);throw Error('Sessão local expirada. Clique em Atualizar.');}const d=await r.json();if(!r.ok)throw Error(d.error||'Consulta indisponível.');return d;}
 function kpis(target,values){const row=n('div','kpis');for(const [title,value,hint]of values){const box=n('section','card kpi');const c=/repasse|l[ií]quido/i.test(title)?'#16a34a':/cancel|reembol|devolu|sem estoque/i.test(title)?'#ef4444':/comiss|taxa|desconto/i.test(title)?'#f59e0b':/pedidos pagos|pagos/i.test(title)?'#2c83ff':/ticket/i.test(title)?'#06b6d4':/carrinho|abandon|estoque baixo|cat[aá]logo|produto/i.test(title)?'#8b5cf6':'#7c3aed';const ic=/repasse|l[ií]quido/i.test(title)?'ph-coins':/comiss|taxa/i.test(title)?'ph-percent':/desconto|cupom/i.test(title)?'ph-tag':/cancel/i.test(title)?'ph-x-circle':/reembol|devolu/i.test(title)?'ph-arrow-u-up-left':/pedidos/i.test(title)?'ph-bag-simple':/unidade/i.test(title)?'ph-package':/ticket/i.test(title)?'ph-receipt':/carrinho|abandon/i.test(title)?'ph-shopping-cart-simple':/estoque|produto|cat[aá]logo/i.test(title)?'ph-package':/vendas|faturamento|bruto/i.test(title)?'ph-currency-circle-dollar':'ph-chart-line';box.style.borderLeft='4px solid '+c;const head=n('div','kpi-label');const iconBox=n('span','kpi-icon');iconBox.style.background=c+'22';iconBox.style.color=c;iconBox.style.width='26px';iconBox.style.height='26px';iconBox.style.fontSize='15px';iconBox.setAttribute('aria-hidden','true');iconBox.append(n('i','ph '+ic));head.append(iconBox,n('span','',title));const val=n('strong','',value);val.style.color=c;box.append(head,val,n('small','',hint||''));row.append(box);}target.append(row);}
 function stats(){return C.summarize(resource.orders.data.orders,$('start').value,$('end').value);}
 function show(key,paint,target=$('content')){const r=resource[key];if(r.error){target.append(n('p','error',r.error),button('Tentar novamente',()=>load(key)));return false;}if(!r.data){target.append(n('p','loading','Consultando '+({orders:'pedidos',products:'catálogo',checkouts:'carrinhos'}[key])+' da Nuvemshop…'));return false;}paint(r.data);return true;}
 function detail(title,items,totals){const target=$('detail-content');target.replaceChildren(n('h2','',title));const card=panel('Itens');table(card,['Produto','Qtd.','Preço unitário'],items.map(i=>[product(i.title,i.variant||i.sku,i.image),num(i.quantity),money(i.price)]));target.append(card);const grid=n('div','detail-totals');for(const [key,value]of totals)grid.append(n('span','muted',key),n('strong','',value));target.append(grid);$('detail').showModal();}
 function orderDetail(o){detail('Pedido #'+o.number,o.items,[['Criado em',date(o.created)],['Situação',label(o.status)],['Pagamento',label(o.payment)],['Pago em',date(o.paidAt)],['Envio',label(o.shipping)],['Meio',label(o.method)],['Operadora',o.gateway||'Não informado'],['Parcelas',o.installments||'Não informado'],['Subtotal',o.currency==='BRL'?money(o.subtotal):o.currency],['Desconto',o.currency==='BRL'?money(o.discount):o.currency],['Total',o.currency==='BRL'?money(o.total):o.currency],['Total pago pelo cliente',o.currency==='BRL'?money(o.paid):o.currency]]);}
 const inCreated=o=>C.within(o.created,$('start').value,$('end').value);
 const inPaid=o=>C.within(o.paidAt,$('start').value,$('end').value);
 function ranking(target,s){table(target,['Produto','Unidades','Valor dos itens'],s.ranking.slice(0,5).map(p=>[product(p.title,p.sku,p.image),num(p.units),money(p.value)]));}
 function overview(){show('orders',()=>{const s=stats();kpis($('content'),[['Vendas pagas',money(s.revenue),'Por data de pagamento'],['Pedidos pagos',num(s.paid),'Pagos, em reais e não cancelados'],['Ticket médio',money(s.ticket),'Vendas pagas ÷ pedidos pagos'],['Pedidos cancelados',num(s.cancelled),'Criados no período']]);const grid=n('div','grid'),sales=panel('Vendas por dia','Pedidos pagos por data de pagamento · Brasília'),ops=panel('Pedidos criados no período','Situação atual dos pedidos não cancelados');const entries=[];for(let d=$('start').value;d<=$('end').value;d=M.shift(d,1))entries.push([d,s.byDay[d]||0]);drawChart(sales,entries);for(const [key,value]of Object.entries(s.operations)){const line=n('div','ns-operation');line.append(n('span','',label(key)),n('strong','',num(value)));ops.append(line);}ops.append(button('Ver pedidos →',()=>{location.hash='pedidos';},'text-button'));grid.append(sales,ops);$('content').append(grid);const bottom=n('div','grid'),top=panel('Produtos mais vendidos','Itens dos pedidos pagos no período · valores antes de descontos do pedido'),carts=panel('Carrinhos abandonados','Disponíveis nos últimos 30 dias');ranking(top,s);show('checkouts',d=>{const rows=d.checkouts.filter(c=>c.currency==='BRL');carts.append(n('div','chart-summary',num(d.checkouts.length)+' carrinhos'),n('div','chart-summary',money(rows.reduce((sum,c)=>sum+(c.total||0),0))),n('p','caption','Valor dos carrinhos em reais. Não representa venda confirmada. Consulta em '+date(d.queriedAt)+(d.cache?.refreshing?' · Atualizando…':d.cache?.error?' · Últimos dados salvos. '+d.cache.error:'')),button('Ver carrinhos →',()=>{location.hash='carrinhos';},'primary'));},carts);bottom.append(top,carts);$('content').append(bottom);$('content').append(n('p','caption',`${s.missingDate} pedidos pagos criados no período sem data de pagamento, separados do faturamento. ${s.otherCurrency} pagamentos em outras moedas excluídos. Reembolsos totais ou parciais não entram em vendas pagas.`));});}
 function ordersView(){show('orders',d=>{const p=panel('Pedidos da loja','Filtro por data de criação. Abra um pedido para consultar os itens e o pagamento.');$('content').append(p);const rows=d.orders.filter(inCreated),body=n('div');let page=0,filtered=rows;
 const bar=searchBar('Número do pedido, produto ou SKU',(q,status,payment,shipping)=>{page=0;filtered=rows.filter(o=>(!q||[o.number,...o.items.flatMap(i=>[i.title,i.sku])].join(' ').toLowerCase().includes(q.toLowerCase()))&&(!status||o.status===status)&&(!payment||o.payment===payment)&&(!shipping||o.shipping===shipping));paint();},[['Situação',options(rows,'status')],['Pagamento',options(rows,'payment')],['Envio',options(rows,'shipping')]]);p.append(bar.form,body);
 function paint(){body.replaceChildren();table(body,['Pedido','Criado em','Produtos','Total','Pagamento','Envio'],filtered.slice(page*15,page*15+15).map(o=>[button('#'+o.number,()=>orderDetail(o),'row-link'),date(o.created),product(o.items[0]?.title,(o.items.length>1?'+'+(o.items.length-1)+' itens':o.items[0]?.sku),o.items[0]?.image),o.currency==='BRL'?money(o.total):o.currency,badge(o.payment),badge(o.shipping)]));pager(body,filtered.length,page,15,v=>{page=v;paint();});}paint();});}
 function externalLink(title,url){if(!url)return n('span','muted','Não informado');const a=n('a','row-link',title);a.href=url;a.target='_blank';a.rel='noopener noreferrer';return a;}
 function options(rows,key){return [['','Todos'],...[...new Set(rows.map(o=>o[key]).filter(Boolean))].sort().map(v=>[v,label(v)])];}
 function productsView(){show('products',d=>{const variants=d.products.flatMap(p=>p.variants.map(v=>({...v,product:p}))),published=variants.filter(v=>v.product.published),controlled=published.filter(v=>v.managed&&v.stock!==null);kpis($('content'),[['Produtos publicados',num(d.products.filter(p=>p.published).length),'Catálogo atual'],['Produtos ocultos',num(d.products.filter(p=>!p.published).length),'Catálogo atual'],['Variações sem estoque',num(controlled.filter(v=>v.stock<=0).length),'Produtos publicados'],['Estoque baixo',num(controlled.filter(v=>v.stock>0&&v.stock<=5).length),'Até 5 unidades · publicados']]);const p=panel('Produtos e estoque','Posição atual. Uma linha por variação; sem controle de estoque não significa estoque zero.'),body=n('div');let page=0,filtered=variants;
 const bar=searchBar('Produto, SKU ou variação',(q,pub,stock,category)=>{page=0;filtered=variants.filter(v=>(!q||(v.product.title+' '+v.title+' '+v.sku).toLowerCase().includes(q.toLowerCase()))&&(!category||v.product.categories.includes(category))&&(!pub||String(v.product.published)===pub)&&(!stock||(stock==='zero'?v.managed&&v.stock!==null&&v.stock<=0:stock==='low'?v.managed&&v.stock>0&&v.stock<=5:stock==='free'?!v.managed:v.managed&&v.stock===null)));paint();},[['Publicação',[['','Todas'],['true','Publicado'],['false','Oculto']]],['Estoque',[['','Todos'],['zero','Sem estoque'],['low','Estoque baixo'],['free','Sem controle'],['unknown','Não informado']]],['Categoria',[['','Todas'],...[...new Set(d.products.flatMap(p=>p.categories))].sort().map(c=>[c,c])]]]);p.append(bar.form,body);$('content').append(p);
 function paint(){body.replaceChildren();table(body,['Produto','Variação e SKU','Preço','Promocional','Estoque','Publicação',''],filtered.slice(page*20,page*20+20).map(v=>[product(v.product.title,v.product.categories.join(' / '),v.product.image),v.title+' · '+(v.sku||'Sem SKU'),money(v.price),v.promotional===null?'—':money(v.promotional),n('span','badge '+(v.managed&&v.stock!==null?(v.stock<=0?'bad':v.stock<=5?'warn':'good'):''),!v.managed?'Sem controle':v.stock===null?'Não informado':num(v.stock)),n('span','badge '+(v.product.published?'good':''),v.product.published?'Publicado':'Oculto'),externalLink('Ver produto ↗',v.product.url)]));pager(body,filtered.length,page,20,v=>{page=v;paint();});}paint();});}
 function paymentsView(){show('orders',d=>{const s=stats();kpis($('content'),[['Pedidos pagos',num(s.paid),'Por data de pagamento'],['Valor dos pedidos pagos',money(s.revenue),'Total dos pedidos · BRL'],['Sem data de pagamento',num(s.missingDate),'Pagos, criados no período'],['Pagamentos pendentes',num(s.pending),'Pedidos criados no período']]);const p=panel('Pagamentos dos pedidos','Pagos por data de pagamento; pendentes e sem data por criação. Valores dos pedidos, sem estimativa de taxas ou repasses.'),body=n('div');$('content').append(p);const rows=d.orders.filter(o=>inPaid(o)||(!o.paidAt&&inCreated(o)));let filtered=rows,page=0;const bar=searchBar('Número do pedido ou operadora',(q,payment,method)=>{page=0;filtered=rows.filter(o=>(!q||(o.number+' '+o.gateway).toLowerCase().includes(q.toLowerCase()))&&(!payment||o.payment===payment)&&(!method||o.method===method));paint();},[['Situação',options(rows,'payment')],['Meio',options(rows,'method')]]);p.append(bar.form,body);
 function paint(){body.replaceChildren();table(body,['Pedido','Situação','Meio','Operadora','Parcelas','Pago em','Total do pedido'],filtered.slice(page*15,page*15+15).map(o=>[button('#'+o.number,()=>orderDetail(o),'row-link'),badge(o.payment),label(o.method),o.gateway||'Não informado',o.installments?o.installments+'x':'—',date(o.paidAt),o.currency==='BRL'?money(o.total):o.currency]));pager(body,filtered.length,page,15,v=>{page=v;paint();});}paint();});}
 function checkoutsView(){show('checkouts',d=>{const rows=d.checkouts,brl=rows.filter(c=>c.currency==='BRL');kpis($('content'),[['Carrinhos',num(rows.length),'Disponíveis nos últimos 30 dias'],['Valor dos carrinhos',money(brl.reduce((s,c)=>s+(c.total||0),0)),'Somente valores em reais'],['Notificados pela loja',num(rows.filter(c=>c.notified===true).length),'Situação informada pela Nuvemshop'],['Sem estoque disponível',num(rows.filter(c=>c.stock===false).length),'Posição informada pela Nuvemshop']]);const grid=n('div','grid'),p=panel('Carrinhos abandonados','A Nuvemshop pode levar até 6 horas para registrar um abandono.'),selected=panel('Detalhes do carrinho','Selecione um carrinho para consultar os produtos.'),body=n('div');grid.append(p,selected);$('content').append(grid);let filtered=rows,page=0;const age=c=>Math.max(0,(Date.now()-new Date(c.created))/86400000),bucket=c=>age(c)<1?'day':age(c)<3?'three':age(c)<7?'week':'older';
 const bar=searchBar('Produto ou carrinho',(q,a,notice,stock)=>{page=0;filtered=rows.filter(c=>(!q||(c.id+' '+c.items.map(i=>i.title).join(' ')).toLowerCase().includes(q.toLowerCase()))&&(!a||bucket(c)===a)&&(!notice||String(c.notified)===notice)&&(!stock||String(c.stock)===stock));paint();},[['Idade',[['','Todas'],['day','Até 24 horas'],['three','1 a 3 dias'],['week','3 a 7 dias'],['older','Mais de 7 dias']]],['Notificação',[['','Todas'],['true','Notificado'],['false','Não notificado']]],['Estoque',[['','Todos'],['true','Disponível'],['false','Sem estoque']]]]);p.append(bar.form,body);
 function select(c){selected.replaceChildren(n('h2','','Carrinho #'+c.id),n('p','caption','Criado em '+date(c.created)));table(selected,['Produto','Qtd.','Preço'],c.items.map(i=>[product(i.title,i.variant||i.sku,i.image),num(i.quantity),money(i.price)]));selected.append(n('div','chart-summary',c.currency==='BRL'?money(c.total):c.currency),n('p','caption',(c.notified===null?'Notificação não informada':c.notified?'Notificado pela loja':'Não notificado')+' · '+(c.stock===null?'Estoque não informado':c.stock?'Estoque disponível':'Sem estoque disponível')));if(c.url)selected.append(externalLink('Abrir checkout ↗',c.url));}
 function paint(){body.replaceChildren();table(body,['Carrinho','Criado em','Total','Notificado','Estoque'],filtered.slice(page*10,page*10+10).map(c=>[button('#'+c.id,()=>select(c),'row-link'),date(c.created),c.currency==='BRL'?money(c.total):c.currency,c.notified===null?'Não informado':c.notified?'Sim':'Não',n('span','badge '+(c.stock===false?'warn':c.stock===true?'good':''),c.stock===null?'Não informado':c.stock?'Disponível':'Sem estoque')]));pager(body,filtered.length,page,10,v=>{page=v;paint();});selected.replaceChildren(n('h2','','Detalhes do carrinho'));if(filtered.length)select(filtered[page*10]);else empty(selected,'Nenhum carrinho com esses filtros.');}paint();
 const ages=panel('Idade dos carrinhos','Apenas abandonos após a segunda etapa do checkout. Valores não representam vendas confirmadas.');const group=n('div','ns-ages');for(const [key,title]of [['day','Até 24 horas'],['three','1 a 3 dias'],['week','3 a 7 dias'],['older','Mais de 7 dias']]){const count=rows.filter(c=>bucket(c)===key).length,box=n('div');box.append(n('strong','',num(count)),n('p','caption',title));const progress=n('progress');progress.max=Math.max(1,rows.length);progress.value=count;box.append(progress);group.append(box);}ages.append(group);$('content').append(ages);});}
 function rememberControls(){const forms=[...document.querySelectorAll('#content .toolbar')],active=document.activeElement;const saved=forms.map(form=>[...form.querySelectorAll('input,select')].map(e=>({value:e.value,focused:e===active})));return ()=>{document.querySelectorAll('#content .toolbar').forEach((form,i)=>{const fields=[...form.querySelectorAll('input,select')];saved[i]?.forEach((v,j)=>{if(fields[j])fields[j].value=v.value;});if(saved[i])form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));saved[i]?.forEach((v,j)=>{if(v.focused&&fields[j])fields[j].focus({preventScroll:true});});});};}
 function render(preserve=false){const restore=preserve?rememberControls():null;document.querySelectorAll('[data-tab]').forEach(a=>{if(a.dataset.tab===tab)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});document.title=titles[tab]+' · Nuvemshop | Provou Levou';$('content').replaceChildren();document.querySelector('.date-controls').hidden=['produtos','carrinhos'].includes(tab);$('period-note').textContent=tab==='produtos'?'Posição atual do catálogo':tab==='carrinhos'?'Carrinhos disponíveis nos últimos 30 dias':tab==='pedidos'?'Pedidos por data de criação · Brasília':'Vendas por data de pagamento · Brasília';try{({resumo:overview,pedidos:ordersView,produtos:productsView,pagamentos:paymentsView,carrinhos:checkoutsView}[tab])();}catch(e){failure($('content'),e.message,()=>load());}if(restore)restore();updateStatus();}
 function updateStatus(){$('export').disabled=!resource.orders.data;const key=tab==='produtos'?'products':tab==='carrinhos'?'checkouts':'orders';$('updated').textContent=resource[key].data?'Consulta em '+date(resource[key].data.queriedAt)+' · Nuvemshop'+(resource[key].data.cache?.refreshing?' · Atualizando em segundo plano…':resource[key].data.cache?.error?' · Últimos dados salvos. '+resource[key].data.cache.error:' · Dados salvos localmente.'):'Dados ausentes não equivalem a zero.';}

 async function load(only,force=false){clearTimeout(pollTimer);let range;try{range=M.range($('start').value,$('end').value);if((new Date($('end').value)-new Date($('start').value))/86400000>365)throw Error('Selecione até 366 dias.');}catch(e){failure($('content'),e.message);return;}const run=++epoch,keys=['orders','products','checkouts'].filter(k=>force!=='poll'||resource[k].data?.cache?.refreshing);const sameRange=lastRange===$('start').value+':'+$('end').value;lastRange=$('start').value+':'+$('end').value;if(!sameRange)resource.orders={};$('date-label').textContent=shortDate($('start').value)+' – '+shortDate($('end').value);$('date-menu').open=false;const url=new URL(location.href);url.search=new URLSearchParams({start:$('start').value,end:$('end').value});history.replaceState(null,'',url);for(const b of $('presets').children){const v=b.dataset.period,t=M.day(new Date()),end=v==='yesterday'?M.shift(t,-1):t,start=['today','yesterday'].includes(v)?end:M.shift(t,1-Number(v));b.setAttribute('aria-pressed',String($('start').value===start&&$('end').value===end));}if(!sameRange)render();else updateStatus();await Promise.allSettled(keys.map(async k=>{let changed=false;try{const data=await request(k,{...(k==='orders'?{start:$('start').value,end:$('end').value}:{}),...(force===true?{refresh:'1'}:{})});if(run!==epoch)return;changed=resource[k].data?.queriedAt!==data.queriedAt;resource[k]={data};}catch(e){if(run!==epoch)return;if(resource[k].data){resource[k].data.cache={...resource[k].data.cache,error:e.message,refreshing:false};}else{resource[k]={error:e.message};changed=true;}}if(changed)render(sameRange);else updateStatus();}));if(run===epoch&&Object.values(resource).some(r=>r.data?.cache?.refreshing))pollTimer=setTimeout(()=>load(null,'poll'),2000);}
 for(const [value,title]of [['today','Hoje'],['yesterday','Ontem'],['7','7 dias'],['15','15 dias'],['30','30 dias']]){const b=button(title,()=>{const t=M.day(new Date());$('end').value=value==='yesterday'?M.shift(t,-1):t;$('start').value=['today','yesterday'].includes(value)?$('end').value:M.shift(t,1-Number(value));load();});b.dataset.period=value;$('presets').append(b);}
 $('date-form').addEventListener('submit',e=>{e.preventDefault();load();});$('refresh').addEventListener('click',()=>load(null,true));$('close-detail').addEventListener('click',()=>$('detail').close());window.addEventListener('hashchange',()=>{tab=titles[location.hash.slice(1)]?location.hash.slice(1):'resumo';render();});
 $('export').addEventListener('click',()=>{const data=resource.orders.data;if(!data)return;const rows=[['Pedido','Criado em','Pago em','Situação','Pagamento','Total BRL'],...data.orders.filter(inCreated).map(o=>[o.number,o.created,o.paidAt||'',label(o.status),label(o.payment),o.currency==='BRL'&&o.total!==null?(o.total/100).toFixed(2):''])];const csv='\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=n('a');a.href=url;a.download='nuvemshop-pedidos-'+$('start').value+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 try{client=window.supabase.createClient(window.SUPABASE_CONFIG.URL,window.SUPABASE_CONFIG.KEY);const {data:{session}}=await client.auth.getSession();if(!session){location.href='login.html';return;}$('logout').addEventListener('click',async()=>{await client.auth.signOut();location.href='login.html';});tab=titles[location.hash.slice(1)]?location.hash.slice(1):'resumo';await load();setInterval(()=>{if(!document.hidden&&!document.querySelector('input:focus,select:focus,textarea:focus'))load();},60000);}catch(e){failure($('content'),'Não foi possível iniciar o painel. '+e.message);}
});
