document.addEventListener('DOMContentLoaded',async()=>{
 'use strict';
 const M=window.CacifeMetrics,C=window.NSCore,$=id=>document.getElementById(id);
  const n=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
 const money=v=>Number.isFinite(v)?(v/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'Não informado';
 const num=v=>Number.isFinite(v)?v.toLocaleString('pt-BR'):'—';
 const date=v=>v&&Number.isFinite(new Date(v).getTime())?new Date(v).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'short',timeStyle:'short'}):'Não informado';
 const shortDate=v=>v.split('-').reverse().join('/');
 const button=(text,fn,cls='')=>{const b=n('button',cls,text);b.type='button';b.addEventListener('click',fn);return b;};
 const panel=(title,caption)=>{const e=n('section','card');const head=n('div','card-head');head.append(n('h2','',title));e.append(head);if(caption)e.append(n('p','caption',caption));return e;};
 const empty=(target,text)=>target.append(n('p','empty',text));
 function product(title,subtitle,image){const box=n('div','product');if(image){const img=n('img');img.src=image;img.alt='';img.loading='lazy';img.referrerPolicy='no-referrer';img.addEventListener('error',()=>img.replaceWith(n('span','product-placeholder','◉')),{once:true});box.append(img);}else box.append(n('span','product-placeholder','◉'));const copy=n('div');copy.append(n('strong','',title||'Produto'));if(subtitle)copy.append(n('small','',subtitle));box.append(copy);return box;}
 function table(target,headers,rows){const wrap=n('div','table-wrap'),t=n('table'),head=n('thead'),tr=n('tr');headers.forEach(x=>tr.append(n('th','',x)));head.append(tr);t.append(head);const body=n('tbody');rows.forEach(row=>{const tr=n('tr');row.forEach(value=>{const td=n('td');if(value instanceof Node)td.append(value);else td.textContent=value??'Não informado';tr.append(td);});body.append(tr);});t.append(body);wrap.append(t);target.append(wrap);if(!rows.length)empty(target,'Nenhum registro encontrado com estes filtros.');}
 function pager(target,total,page,size,change){const e=n('div','pager');e.append(n('span','',total===null?'Total não informado':`${num(total)} registros · página ${page+1} de ${Math.max(1,Math.ceil(total/size))}`));const controls=n('div');const prev=button('← Anterior',()=>change(page-1)),next=button('Próxima →',()=>change(page+1));prev.disabled=page===0;next.disabled=total===null||((page+1)*size>=total);controls.append(prev,next);e.append(controls);target.append(e);}
 function searchBar(placeholder,onSearch,options=[]){const form=n('form','toolbar');const field=n('label','search','Buscar');const input=n('input');input.type='search';input.placeholder=placeholder;field.append(input);form.append(field);const selects=[];for(const [title,values]of options){const field=n('label','',title),select=n('select');for(const [value,text]of values){const opt=n('option','',text);opt.value=value;select.append(opt);}field.append(select);form.append(field);selects.push(select);}form.append(button('Filtrar',()=>onSearch(input.value.trim(),...selects.map(s=>s.value))));form.addEventListener('submit',e=>{e.preventDefault();onSearch(input.value.trim(),...selects.map(s=>s.value));});selects.forEach(s=>s.addEventListener('change',()=>onSearch(input.value.trim(),...selects.map(s=>s.value))));return {form,input,selects};}
 function failure(target,error,retry){target.replaceChildren(n('p','error',error));if(retry)target.append(button('Tentar novamente',retry));}
 function drawChart(target,entries,previous=[],bars=false){
  if(!entries.length){empty(target,'Sem dados para o gráfico.');return;}
  const NS='http://www.w3.org/2000/svg',wrap=n('div','interactive-chart'),tooltip=n('div','chart-tooltip'),svg=document.createElementNS(NS,'svg');tooltip.hidden=true;tooltip.setAttribute('role','status');tooltip.setAttribute('aria-live','polite');const H=Number(target.dataset.chartH)||240;svg.setAttribute('viewBox','0 0 620 '+H);svg.setAttribute('class','chart');svg.setAttribute('role','group');svg.setAttribute('aria-label',bars?'Visitas diárias. Passe o mouse, toque ou use Tab para ver detalhes.':'Vendas diárias. Passe o mouse, toque ou use Tab para ver detalhes.');
  const add=(tag,attrs,text)=>{const e=document.createElementNS(NS,tag);for(const [k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;svg.append(e);return e;};
  const max=Math.max(1,...entries.map(x=>x[1]),...previous.map(x=>x[1]));for(let i=0;i<5;i++){const y=15+i*(H-56)/4;add('line',{x1:58,x2:600,y1:y,y2:y,stroke:'#eef0f3'});add('text',{x:50,y:y+4,'text-anchor':'end'},bars?num(Math.round(max*(1-i/4))):'R$ '+Math.round(max*(1-i/4)/100).toLocaleString('pt-BR'));}
  const x=i=>70+i*520/Math.max(1,entries.length-1),y=v=>(H-41)-v/max*(H-56);
  const line=(rows,color,dash)=>{const e=add('polyline',{points:rows.map((d,i)=>x(i)+','+y(d[1])).join(' '),fill:'none',stroke:color,'stroke-width':2.5});if(dash)e.setAttribute('stroke-dasharray','6 6');};if(previous.length)line(previous,'#9ca3af',true);
  if(bars)entries.forEach((d,i)=>add('rect',{x:x(i)-Math.min(10,200/entries.length),y:y(d[1]),width:Math.min(20,400/entries.length),height:(H-41)-y(d[1]),rx:3,fill:'#2c83ff'}));else{line(entries,'#2c83ff');entries.forEach((d,i)=>add('circle',{cx:x(i),cy:y(d[1]),r:3,fill:'#2c83ff'}));}
  for(const i of [...new Set([0,Math.floor((entries.length-1)/2),entries.length-1])])add('text',{x:x(i),y:H-16,'text-anchor':'middle'},entries[i][0].slice(5).split('-').reverse().join('/'));
  const guide=add('line',{x1:70,x2:70,y1:12,y2:H-40,stroke:'#2c83ff','stroke-width':1,'stroke-dasharray':'3 3',visibility:'hidden'});
  function show(i){const d=entries[i];tooltip.replaceChildren(n('strong','',shortDate(d[0].slice(0,10))),n('div','',(bars?'Visitas: ':'Vendas: ')+(bars?num(d[1]):money(d[1]))));if(!bars&&previous[i]){const p=previous[i];tooltip.append(n('div','',shortDate(p[0].slice(0,10))+' · anterior: '+money(p[1])));if(p[1])tooltip.append(n('small','',(d[1]>=p[1]?'↑ ':'↓ ')+Math.abs((d[1]/p[1]-1)*100).toLocaleString('pt-BR',{maximumFractionDigits:1})+'%'));}tooltip.hidden=false;guide.setAttribute('x1',x(i));guide.setAttribute('x2',x(i));guide.setAttribute('visibility','visible');const width=wrap.clientWidth,position=x(i)/620*width;tooltip.style.left=Math.max(8,Math.min(width-tooltip.offsetWidth-8,position-tooltip.offsetWidth/2))+'px';}
  function hide(){tooltip.hidden=true;guide.setAttribute('visibility','hidden');}
  entries.forEach((d,i)=>{const step=520/Math.max(1,entries.length-1),left=entries.length===1?58:Math.max(58,x(i)-step/2),right=entries.length===1?602:Math.min(602,x(i)+step/2);const hit=add('rect',{x:left,y:5,width:right-left,height:H-38,fill:'transparent',tabindex:0,role:'button','aria-label':shortDate(d[0].slice(0,10))+': '+(bars?num(d[1])+' visitas':money(d[1]))+(!bars&&previous[i]?'; anterior '+money(previous[i][1]):'')});hit.addEventListener('pointerenter',()=>show(i));hit.addEventListener('pointermove',()=>show(i));hit.addEventListener('click',()=>show(i));hit.addEventListener('focus',()=>show(i));hit.addEventListener('blur',hide);hit.addEventListener('keydown',event=>{if(event.key==='Escape')hide();if(event.key==='Enter'||event.key===' '){event.preventDefault();show(i);}});});wrap.addEventListener('pointerleave',hide);wrap.append(svg,tooltip);target.append(wrap);
 }
 const names={wallet:'Carteira digital',mobile:'Celular',shipped:'Enviado',delivered:'Entregue',not_delivered:'Não entregue',other:'Outro',custom:'Personalizado',paid:'Pago',pending:'Pendente',authorized:'Autorizado',partially_paid:'Parcialmente pago',refunded:'Reembolsado',partially_refunded:'Reembolso parcial',voided:'Anulado',abandoned:'Abandonado',open:'Aberto',closed:'Fechado',cancelled:'Cancelado',unpacked:'A preparar',unfulfilled:'A enviar',fulfilled:'Enviado',store:'Loja virtual',meli:'Mercado Livre',api:'Integração',form:'Manual',pos:'Ponto de venda',pix:'Pix',credit_card:'Cartão de crédito',debit_card:'Cartão de débito',boleto:'Boleto',bank_transfer:'Transferência',wire_transfer:'Transferência',cash:'Dinheiro'};
 const label=v=>names[v]||v||'Não informado';
 const badge=v=>n('span','badge '+(['paid','fulfilled'].includes(v)?'good':['cancelled','voided'].includes(v)?'bad':v==='pending'?'warn':''),label(v));
 const resource={orders:{},previous:{},products:{},checkouts:{}};let client,csrfPromise,epoch=0,tab='resumo',pollTimer,lastRange='';
 const titles={resumo:'Resumo',pedidos:'Pedidos',produtos:'Produtos',estoque:'Estoque',pagamentos:'Pagamentos',carrinhos:'Carrinhos abandonados'};
 const today=M.day(new Date());$('end').value=today;$('start').value=M.shift(today,-29);
 const params=new URLSearchParams(location.search);if(params.get('start')&&params.get('end')){try{M.range(params.get('start'),params.get('end'));$('start').value=params.get('start');$('end').value=params.get('end');}catch{}}
 async function request(route,query={}){const {data:{session}}=await client.auth.getSession();if(!session){location.href='login.html';throw Error('Entre novamente.');}const key=session.user.id+':nuvemshop:'+route+':'+new URLSearchParams(query);return window.CacifeFastData.get(key,()=>networkRequest(route,query),query.refresh==='1');}
 async function networkRequest(route,query={},retried=false){const {data:{session}}=await client.auth.getSession();if(!session){location.href='login.html';throw Error('Entre novamente.');}if(!csrfPromise)csrfPromise=fetch('/api/session').then(async r=>{if(!r.ok)throw Error('Servidor local indisponível.');return r.json();}).catch(e=>{csrfPromise=null;throw e;});const {csrf}=await csrfPromise;const r=await fetch('/api/channels/nuvemshop/workspace/'+route+'?'+new URLSearchParams(query),{headers:{Authorization:'Bearer '+session.access_token,'X-Cacife-Local':csrf}});if(r.status===403){csrfPromise=null;if(!retried)return networkRequest(route,query,true);throw Error('Sessão local expirada. Clique em Atualizar.');}const d=await r.json();if(!r.ok)throw Error(d.error||'Consulta indisponível.');return d;}
 // Cards das abas no mesmo desenho do Resumo/Pedidos (ícone, faixinha, valor e explicação).
 function kpis(target,values){const strip=n('section','card ml-strip');strip.style.gridTemplateColumns='repeat('+values.length+',minmax(0,1fr))';for(const [title,value,hint]of values){const ic=/repasse|l[ií]quido/i.test(title)?'ph-coins':/comiss|taxa/i.test(title)?'ph-percent':/desconto|cupom/i.test(title)?'ph-tag':/cancel/i.test(title)?'ph-x-circle':/reembol|devolu/i.test(title)?'ph-arrow-u-up-left':/pendente/i.test(title)?'ph-hourglass-medium':/notificad/i.test(title)?'ph-bell':/sem estoque/i.test(title)?'ph-warning-circle':/estoque baixo/i.test(title)?'ph-trend-down':/oculto/i.test(title)?'ph-eye-slash':/publicad/i.test(title)?'ph-storefront':/pedidos/i.test(title)?'ph-bag-simple':/unidade/i.test(title)?'ph-package':/carrinho|abandon/i.test(title)?'ph-shopping-cart-simple':/valor|vendas|faturamento|bruto/i.test(title)?'ph-currency-circle-dollar':'ph-chart-line';strip.append(kpiCard(title,ic,value,{text:hint||'',cls:''}));}target.append(strip);}
 function stats(){return C.summarize(resource.orders.data.orders,$('start').value,$('end').value);}
 function show(key,paint,target=$('content')){const r=resource[key];if(r.error){target.append(n('p','error',r.error),button('Tentar novamente',()=>load(key)));return false;}if(!r.data){target.append(n('p','loading','Consultando '+({orders:'pedidos',products:'catálogo',checkouts:'carrinhos'}[key])+' da Nuvemshop…'));return false;}paint(r.data);return true;}
 function detail(title,items,totals){const target=$('detail-content');target.replaceChildren(n('h2','',title));const card=panel('Itens');table(card,['Produto','Qtd.','Preço unitário'],items.map(i=>[product(i.title,i.variant||i.sku,i.image),num(i.quantity),money(i.price)]));target.append(card);const grid=n('div','detail-totals');for(const [key,value]of totals)grid.append(n('span','muted',key),n('strong','',value));target.append(grid);$('detail').showModal();}
 function orderDetail(o){detail('Pedido #'+o.number,o.items,[['Criado em',date(o.created)],['Situação',label(o.status)],['Pagamento',label(o.payment)],['Pago em',date(o.paidAt)],['Envio',label(o.shipping)],['Meio',label(o.method)],['Operadora',o.gateway||'Não informado'],['Parcelas',o.installments||'Não informado'],['Subtotal',o.currency==='BRL'?money(o.subtotal):o.currency],['Desconto',o.currency==='BRL'?money(o.discount):o.currency],['Total',o.currency==='BRL'?money(o.total):o.currency],['Total pago pelo cliente',o.currency==='BRL'?money(o.paid):o.currency]]);}
 const inCreated=o=>C.within(o.created,$('start').value,$('end').value);
 const inPaid=o=>C.within(o.paidAt,$('start').value,$('end').value);
 function ranking(target,s){table(target,['Produto','Unidades','Valor dos itens'],s.ranking.slice(0,5).map(p=>[product(p.title,p.sku,p.image),num(p.units),money(p.value)]));}
 // Comparação com o período anterior (inverse=true quando subir é ruim).
 function prevStats(){if(!resource.previous.data)return null;try{const e=M.shift($('start').value,-1),st=M.range($('start').value,$('end').value).previous.slice(0,10);return C.summarize(resource.previous.data.orders,st,e);}catch(_){return null;}}
 function compare(cur,old,inverse=false){if(resource.previous.error)return {text:'Comparação indisponível',cls:''};if(old===undefined)return {text:'Consultando período anterior…',cls:''};if(!old)return {text:'Sem base anterior',cls:''};const pct=(cur/old-1)*100,up=pct>=0;return {text:(up?'▲ ':'▼ ')+Math.abs(pct).toLocaleString('pt-BR',{maximumFractionDigits:1})+'%',cls:(up!==inverse)?'up':'down'};}
 function kpiCard(title,icon,value,cmp){const c=n('div','ml-kpi');const h=n('div','ml-kpi-head'),ic=n('span','ml-kpi-icon');ic.setAttribute('aria-hidden','true');ic.append(n('i','ph '+icon));h.append(ic,n('span','',title),n('i','ml-kpi-bar'));const d=n('div','ml-kpi-delta');d.append(n('span',cmp.cls,cmp.text));if(cmp.cls)d.append(n('small','',' vs. anterior'));c.append(h,n('strong','',value),d);return c;}
 const unitsOf=st=>st.ranking.reduce((t,p)=>t+(p.units||0),0);
 function overview(){show('orders',()=>{const s=stats(),p=prevStats(),pv=k=>p?p[k]:(resource.previous.error?null:undefined);
  const cartRows=resource.checkouts.data?.checkouts||null,cartValue=cartRows?cartRows.filter(c=>c.currency==='BRL').reduce((t,c)=>t+(c.total||0),0):null;
  const block=n('section','card ml-block'),four=n('div','ml-four');
  four.append(kpiCard('Pedidos pagos','ph-bag-simple',num(s.paid),compare(s.paid,pv('paid'))),
   kpiCard('Unidades vendidas','ph-package',num(unitsOf(s)),compare(unitsOf(s),p?unitsOf(p):pv('paid'))),
   kpiCard('Carrinhos abandonados','ph-shopping-cart-simple',cartValue===null?'—':money(cartValue),{text:cartRows?num(cartRows.length)+' carrinhos · últimos 30 dias':(resource.checkouts.error?'Consulta indisponível':'Consultando carrinhos…'),cls:''}),
   kpiCard('Pagamentos pendentes','ph-hourglass-medium',num(s.pending),compare(s.pending,pv('pending'),true)));
  const dark=n('div','ml-dark'),dh=n('div','ml-dark-head'),logo=n('span','platform-icon channel-emblem nuvemshop');logo.setAttribute('aria-hidden','true');const li=n('img');li.src='nuvemshop-logo.png';li.alt='';logo.append(li);dh.append(logo,n('span','','Vendas pagas'));
  const vc=compare(s.revenue,pv('revenue')),main=n('div','ml-dark-main');main.append(n('small','','Loja própria · por data de pagamento'),n('strong','',money(s.revenue)),n('span','ml-dark-delta '+vc.cls,vc.text+(vc.cls?' vs. período anterior':'')));
  const foot=n('div','ml-dark-foot');foot.append(n('small','','Sem comissão de marketplace'),n('strong','','Líquido = bruto'));dark.append(dh,main,foot);block.append(four,dark);$('content').append(block);
  const row=n('div','grid ns-row3'),sales=panel('Vendas por dia','Pedidos pagos por data de pagamento · Brasília'),ops=panel('Pedidos criados no período','Situação atual dos pedidos não cancelados'),carts=panel('Carrinhos abandonados','Disponíveis nos últimos 30 dias');
  sales.dataset.chartH='270';sales.append(n('div','chart-summary',money(s.revenue)),n('p','caption',shortDate($('start').value)+' a '+shortDate($('end').value)));const entries=[];for(let d=$('start').value;d<=$('end').value;d=M.shift(d,1))entries.push([d,s.byDay[d]||0]);drawChart(sales,entries);
  for(const [key,value]of Object.entries(s.operations)){const line=n('div','ns-operation');line.append(n('span','',label(key)),n('strong','',num(value)));ops.append(line);}const canc=n('div','ns-operation');canc.append(n('span','','Cancelados'),n('strong','',num(s.cancelled)));ops.append(canc,button('Ver pedidos →',()=>{location.hash='pedidos';},'link-button'));
  show('checkouts',d=>{const rows=d.checkouts.filter(c=>c.currency==='BRL');carts.append(n('div','chart-summary',money(rows.reduce((sum,c)=>sum+(c.total||0),0))),n('p','caption',num(d.checkouts.length)+' carrinhos · valor em reais. Não representa venda confirmada.'),button('Ver carrinhos →',()=>{location.hash='carrinhos';},'link-button'));},carts);
  row.append(sales,ops,carts);$('content').append(row);
  const top=panel('Produtos mais vendidos','Itens dos pedidos pagos no período · valores antes de descontos do pedido');table(top,['Produto','Unidades','Valor dos itens'],s.ranking.slice(0,10).map(p=>[product(p.title,p.sku,p.image),num(p.units),money(p.value)]));$('content').append(top);
  $('content').append(n('p','caption',`${s.missingDate} pedidos pagos criados no período sem data de pagamento, separados do faturamento. ${s.otherCurrency} pagamentos em outras moedas excluídos. Reembolsos totais ou parciais não entram em vendas pagas.`));});}
 // ---------- Pedidos, Pagamentos e Estoque no desenho do TikTok Shop (channel-kit.js), cores da Nuvemshop ----------
 const NS_KIT={accent:'#2c83ff',accent2:'#0a2540'};
 const nsOrderState={},nsPayState={},nsStockState={};
 const nsTone=v=>['paid','fulfilled','shipped','delivered'].includes(v)?'g':['cancelled','voided','refunded','abandoned'].includes(v)?'rd':['pending','authorized','partially_paid','partially_refunded','unpacked','unfulfilled'].includes(v)?'am':'gy';
 const NS_PAL=['#2c83ff','#0a2540','#16a34a','#d97706','#8b5cf6','#06b6d4','#ec4899','#64748b'];
 function ordersView(){show('orders',d=>{const K=window.ChannelKit;if(!K)return;const H=K.h;const s=stats(),pp=prevStats(),pv=k=>pp?pp[k]:(resource.previous.error?0:undefined);
  const rows=d.orders.filter(inCreated);
  const groupOf=o=>o.status==='cancelled'?'cancelado':o.payment!=='paid'?'naopago':o.shipping==='delivered'?'entregue':['fulfilled','shipped'].includes(o.shipping)?'enviado':'enviar';
  K.ordersView($('content'),{...NS_KIT,state:nsOrderState,
   before:'<div style="margin-bottom:16px">'+K.kpis([['Pedidos pagos','ph-bag-simple',H.esc(num(s.paid)),H.delta(s.paid,pv('paid'))],['Pedidos cancelados','ph-x-circle',H.esc(num(s.cancelled)),H.delta(s.cancelled,pv('cancelled'),true)],['Pagamentos pendentes','ph-hourglass-medium',H.esc(num(s.pending)),H.delta(s.pending,pv('pending'),true)]],3)+'</div>',
   groups:[{key:'',label:'Todos',color:'#0a2540'},{key:'naopago',label:'Aguardando pagamento',color:'#d97706'},{key:'enviar',label:'A enviar',color:'#2c83ff'},{key:'enviado',label:'Enviados',color:'#06b6d4'},{key:'entregue',label:'Entregues',color:'#16a34a'},{key:'cancelado',label:'Cancelados',color:'#dc2626',red:true}],groupOf,rows,
   title:'Pedidos da loja',caption:'Filtro por data de criação · abra um pedido para ver os itens e o pagamento',search:'Número do pedido, produto ou SKU',text:o=>[o.number,...o.items.flatMap(i=>[i.title,i.sku])].join(' '),
   selects:[{label:'Pagamento',options:[['','Todos os pagamentos'],...options(rows,'payment').slice(1)],test:(o,v)=>o.payment===v},{label:'Envio',options:[['','Todos os envios'],...options(rows,'shipping').slice(1)],test:(o,v)=>o.shipping===v}],
   columns:[{h:'Pedido',cls:'nw',cell:(o,i)=>H.openBtn('#'+o.number,i)},{h:'Criado em',cls:'nw',cell:o=>H.esc(H.when(o.created))},
    {h:'Produtos',cell:o=>{const it=o.items[0]||{};return `<span class="ck-pn">${H.foto(it.image)}${H.pname(it.title||'Produto',260,H.esc(o.items.length>1?'+'+(o.items.length-1)+' itens':[it.variant,it.sku].filter(Boolean).join(' · ')))}</span>`;}},
    {h:'Total',cls:'r',cell:o=>`<b>${H.esc(o.currency==='BRL'?money(o.total):o.currency)}</b>`},{h:'Pagamento',cls:'nw',cell:o=>H.pill(label(o.payment),nsTone(o.payment))},{h:'Envio',cls:'nw',cell:o=>H.pill(label(o.shipping),nsTone(o.shipping))}],
   onOpen:o=>orderDetail(o),rowClick:true});});}
 function externalLink(title,url){if(!url)return n('span','muted','Não informado');const a=n('a','row-link',title);a.href=url;a.target='_blank';a.rel='noopener noreferrer';return a;}
 function options(rows,key){return [['','Todos'],...[...new Set(rows.map(o=>o[key]).filter(Boolean))].sort().map(v=>[v,label(v)])];}
 // Aba Produtos: vendas por produto no desenho do TikTok Shop (channel-kit.js) em cima; catálogo e estoque embaixo.
 function salesByProduct(){const K=window.ChannelKit,kit=NS_KIT;if(!K)return;const box=n('div');box.style.marginBottom='18px';$('content').append(box);const r=resource.orders;if(r.error){K.message(box,r.error,kit);return;}if(!r.data){K.message(box,'Consultando pedidos da Nuvemshop…',kit);return;}
  const start=$('start').value,end=$('end').value;let rows,prevRows=null;try{rows=C.itemRows(r.data.orders,start,end);if(resource.previous.data)prevRows=C.itemRows(resource.previous.data.orders,M.range(start,end).previous.slice(0,10),M.shift(start,-1));}catch(e){K.message(box,e.message,kit);return;}
  K.productsView(box,{...kit,rows,prevRows,prevLoading:!resource.previous.data&&!resource.previous.error,start,end,caption:'pedidos pagos no período (data do pagamento)'});}
 // Estoque (desenho do Estoque do TikTok): ritmo de venda = unidades pagas no período ÷ dias do período.
 function stockSection(d){const K=window.ChannelKit;if(!K)return;const H=K.h,start=$('start').value,end=$('end').value,days=Math.max(1,K.dayList(start,end).length);
  const sold=new Map();let salesOk=false;if(resource.orders.data){try{for(const r of C.itemRows(resource.orders.data.orders,start,end)){const k=r.variantId?'v:'+r.variantId:'p:'+r.id;sold.set(k,(sold.get(k)||0)+r.qty);}salesOk=true;}catch{}}
  const variants=d.products.flatMap(p=>p.variants.map(v=>{const u=sold.get('v:'+v.id)||(p.variants.length===1?sold.get('p:'+p.id)||0:0),perDay=u/days,ctrl=v.managed&&v.stock!==null;return {...v,product:p,u,perDay,ctrl,dias:ctrl&&v.stock>0&&perDay>0?v.stock/perDay:null};}));
  const published=variants.filter(v=>v.product.published),controlled=published.filter(v=>v.ctrl);
  const esgVende=controlled.filter(v=>v.stock<=0&&v.u>0),acabando=controlled.filter(v=>v.stock>0&&v.dias!==null&&v.dias<=10);
  const alerts=[...esgVende,...acabando].sort((a,b)=>b.u-a.u||(a.dias??0)-(b.dias??0));
  const perDayTxt=v=>v.perDay?v.perDay.toLocaleString('pt-BR',{maximumFractionDigits:1}):'0';
  const diasTxt=v=>v.stock<=0?'Esgotado':v.dias<1?'< 1 dia':Math.floor(v.dias)+(Math.floor(v.dias)===1?' dia':' dias');
  const groupOf=v=>!v.managed?'free':v.stock===null?'unknown':v.stock<=0?'zero':v.stock<=5?'low':'ok';
  const cats=[...new Set(d.products.flatMap(p=>p.categories))].sort();
  const vendas=salesOk?'':' · consultando vendas…';
  K.stockView($('content'),{...NS_KIT,
   kpis:[['Variações publicadas','ph-stack',H.esc(num(published.length)),H.muted(num(d.products.filter(p=>p.published).length)+' produtos publicados')],['Esgotados que vendem','ph-warning-circle',`<span class="ck-red">${H.esc(num(esgVende.length))}</span>`,H.muted('venderam no período'+vendas)],['Acabando (até 10 dias)','ph-hourglass-low',H.esc(num(acabando.length)),H.muted('no ritmo de venda do período'+vendas)],['Sem estoque (total)','ph-prohibit',H.esc(num(controlled.filter(v=>v.stock<=0).length)),(k=>H.muted(num(k)+(k===1?' produto oculto':' produtos ocultos')))(d.products.filter(p=>!p.published).length)]],
   repor:{title:'Repor primeiro',caption:'As variações que mais vendem entre esgotadas e acabando · ritmo = vendas do período ÷ '+num(days)+' dias',items:alerts.map(v=>({title:v.product.title,image:v.product.image,sub:v.title+' · vende '+perDayTxt(v)+'/dia',pillText:diasTxt(v),pillTone:v.stock<=0||v.dias<=3?'rd':'am'})),
    csv:{name:'nuvemshop-repor-estoque.csv',rows:()=>[['Produto','Variação','SKU','Em estoque','Vendas no período','Vende por dia','Acaba em (dias)','Situação'],...alerts.map(v=>[v.product.title,v.title,v.sku||'',v.stock,v.u,perDayTxt(v),v.stock>0?Math.floor(v.dias):0,v.stock>0?'Acabando':'Esgotado'])]}},
   list:{state:nsStockState,tiles:false,pageSize:20,rows:variants,groupOf,
    groups:[{key:'',label:'Todas'},{key:'zero',label:'Sem estoque'},{key:'low',label:'Estoque baixo'},{key:'ok',label:'Com estoque'},{key:'free',label:'Sem controle'},{key:'unknown',label:'Não informado'}],
    title:'Produtos e estoque',caption:'Posição atual · uma linha por variação · sem controle de estoque não significa estoque zero',search:'Produto, SKU ou variação',text:v=>v.product.title+' '+v.title+' '+(v.sku||''),
    selects:[{label:'Publicação',options:[['','Publicados e ocultos'],['true','Publicado'],['false','Oculto']],test:(v,x)=>String(v.product.published)===x},{label:'Categoria',options:[['','Todas as categorias'],...cats.map(c=>[c,c])],test:(v,x)=>v.product.categories.includes(x)}],
    columns:[{h:'Produto',cell:v=>`<span class="ck-pn">${H.foto(v.product.image)}${H.pname(v.product.title,280,H.esc(v.product.categories.join(' / ')))}</span>`},{h:'Variação',cls:'nw',cell:v=>`${H.esc(v.title)}<small>${H.esc(v.sku||'Sem SKU')}</small>`},
     {h:'Preço',cls:'r',cell:v=>`${H.esc(money(v.price))}${v.promotional!==null&&v.promotional!==undefined?`<small>promo ${H.esc(money(v.promotional))}</small>`:''}`},
     {h:'Em estoque',cls:'r',cell:v=>!v.managed?'<span class="ck-mut">Sem controle</span>':v.stock===null?'<span class="ck-mut">—</span>':`<b${v.stock<=0?' class="ck-red"':''}>${H.esc(num(v.stock))}</b>`},
     {h:'Vende por dia',cls:'r',cell:v=>salesOk?H.esc(perDayTxt(v)):'<span class="ck-mut">—</span>'},
     {h:'Acaba em',cls:'nw',cell:v=>{if(!v.ctrl)return '<span class="ck-mut">—</span>';if(v.stock<=0)return H.pill('Esgotado','rd');if(v.dias===null)return '<span class="ck-mut">sem vendas</span>';const w=Math.max(8,Math.min(100,v.dias/10*100));return `<span style="font-size:12.5px;font-weight:600">${H.esc(diasTxt(v))}</span><span class="ck-prog" style="height:6px;margin-top:5px;width:110px"><i style="width:${w}%;background:${v.dias<=3?'#dc2626':v.dias<=10?'#d97706':'#16a34a'}"></i></span>`;}},
     {h:'Publicação',cls:'nw',cell:v=>H.pill(v.product.published?'Publicado':'Oculto',v.product.published?'g':'gy')},
     {h:'',cls:'r',cell:v=>{const u=H.safeUrl(v.product.url);return u?`<a class="ck-link" href="${H.esc(u)}" target="_blank" rel="noopener noreferrer">Ver produto ↗</a>`:'<span class="ck-mut">—</span>';}}]}});}
 function productsView(){salesByProduct();}function estoqueView(){show('products',d=>stockSection(d));}
 function paymentsView(){show('orders',d=>{const K=window.ChannelKit;if(!K)return;const H=K.h;const s=stats(),pp=prevStats(),pv=k=>pp?pp[k]:(resource.previous.error?0:undefined);
  const start=$('start').value,end=$('end').value;
  const paidRows=d.orders.filter(o=>inPaid(o)&&o.status!=='cancelled'&&o.payment==='paid'&&o.currency==='BRL');
  const sum=k=>paidRows.reduce((t,o)=>t+(Number.isSafeInteger(o[k])?o[k]:0),0),sub=sum('subtotal'),disc=sum('discount'),tot=sum('total'),frete=tot-(sub-disc);
  const byM={};for(const o of paidRows){const k=o.method||'other';const g=byM[k]||(byM[k]={n:0,v:0,gw:new Set()});g.n++;g.v+=o.total||0;if(o.gateway)g.gw.add(o.gateway);}
  const dates=K.dayList(start,end);
  const rows=d.orders.filter(o=>inPaid(o)||(!o.paidAt&&inCreated(o)));
  const stc={};for(const o of rows)stc[o.payment||'none']=(stc[o.payment||'none']||0)+1;
  K.financeView($('content'),{...NS_KIT,logo:'nuvemshop-logo.png',
   hero:{title:'Vendas pagas',value:s.revenue,sub:H.delta(s.revenue,pv('revenue')).replace('vs. anterior','vs. período anterior'),foot:H.esc(num(s.paid)+' pedidos pagos · ticket médio '+money(s.ticket))},
   kpis:[['Pedidos pagos','ph-bag-simple',H.esc(num(s.paid)),H.delta(s.paid,pv('paid'))],['Pagamentos pendentes','ph-hourglass-medium',H.esc(num(s.pending)),H.delta(s.pending,pv('pending'),true)],['Sem data de pagamento','ph-calendar-x',H.esc(num(s.missingDate)),H.muted('pagos, criados no período')]],
   waterfall:{title:'Do subtotal ao total pago',caption:'Pedidos pagos no período · a Nuvemshop não informa as taxas do meio de pagamento',steps:[['Subtotal',sub,'t'],['Descontos',-disc],['Frete e ajustes',frete],['Total',tot,'t']]},
   side:{title:'Por meio de pagamento',caption:'Pedidos pagos no período',rows:Object.entries(byM).sort((a,b)=>b[1].v-a[1].v).map(([m,g],i)=>({label:label(m),sub:[...g.gw].join(', '),n:num(g.n)+' pedidos',value:g.v,color:NS_PAL[i%8]})),total:{label:'Total pago',value:tot}},
   bars:{title:'Vendas pagas por dia',caption:'Valor dos pedidos pela data do pagamento',dates,vals:dates.map(x=>s.byDay[x]||0),name:'Pago',empty:'Sem vendas'},
   list:{state:nsPayState,tiles:false,rows,pageSize:15,groupOf:o=>o.payment||'none',groups:[{key:'',label:'Todos'},...Object.keys(stc).sort((a,b)=>stc[b]-stc[a]).map(k=>({key:k,label:k==='none'?'Não informado':label(k)}))],
    title:'Pagamentos dos pedidos',caption:'Pagos por data de pagamento; pendentes e sem data por criação',search:'Número do pedido ou operadora',text:o=>o.number+' '+(o.gateway||''),
    selects:[{label:'Meio',options:[['','Todos os meios'],...options(rows,'method').slice(1)],test:(o,v)=>o.method===v}],
    columns:[{h:'Pedido',cls:'nw',cell:(o,i)=>H.openBtn('#'+o.number,i)},{h:'Situação',cls:'nw',cell:o=>H.pill(label(o.payment),nsTone(o.payment))},{h:'Meio',cls:'nw',cell:o=>H.esc(label(o.method))},{h:'Operadora',cls:'nw',cell:o=>H.esc(o.gateway||'Não informado')},{h:'Parcelas',cls:'r',cell:o=>o.installments?H.esc(o.installments+'x'):'—'},{h:'Pago em',cls:'nw',cell:o=>H.esc(H.when(o.paidAt))},{h:'Total do pedido',cls:'r',cell:o=>`<b>${H.esc(o.currency==='BRL'?money(o.total):o.currency)}</b>`}],
    onOpen:o=>orderDetail(o),rowClick:true,
    csv:{name:'nuvemshop-pagamentos-'+start+'.csv',rows:list=>[['Pedido','Situação','Meio','Operadora','Parcelas','Pago em','Total BRL'],...list.map(o=>[o.number,label(o.payment),label(o.method),o.gateway||'',o.installments||'',o.paidAt||'',o.currency==='BRL'?H.csvMoney(o.total):''])]}}});});}
 function checkoutsView(){show('checkouts',d=>{const rows=d.checkouts,brl=rows.filter(c=>c.currency==='BRL');kpis($('content'),[['Carrinhos',num(rows.length),'Disponíveis nos últimos 30 dias'],['Valor dos carrinhos',money(brl.reduce((s,c)=>s+(c.total||0),0)),'Somente valores em reais'],['Notificados pela loja',num(rows.filter(c=>c.notified===true).length),'Situação informada pela Nuvemshop'],['Sem estoque disponível',num(rows.filter(c=>c.stock===false).length),'Posição informada pela Nuvemshop']]);const grid=n('div','grid'),p=panel('Carrinhos abandonados','A Nuvemshop pode levar até 6 horas para registrar um abandono.'),selected=panel('Detalhes do carrinho','Selecione um carrinho para consultar os produtos.'),body=n('div');grid.append(p,selected);$('content').append(grid);let filtered=rows,page=0;const age=c=>Math.max(0,(Date.now()-new Date(c.created))/86400000),bucket=c=>age(c)<1?'day':age(c)<3?'three':age(c)<7?'week':'older';
 const bar=searchBar('Produto ou carrinho',(q,a,notice,stock)=>{page=0;filtered=rows.filter(c=>(!q||(c.id+' '+c.items.map(i=>i.title).join(' ')).toLowerCase().includes(q.toLowerCase()))&&(!a||bucket(c)===a)&&(!notice||String(c.notified)===notice)&&(!stock||String(c.stock)===stock));paint();},[['Idade',[['','Todas'],['day','Até 24 horas'],['three','1 a 3 dias'],['week','3 a 7 dias'],['older','Mais de 7 dias']]],['Notificação',[['','Todas'],['true','Notificado'],['false','Não notificado']]],['Estoque',[['','Todos'],['true','Disponível'],['false','Sem estoque']]]]);p.append(bar.form,body);
 function select(c){selected.replaceChildren(n('h2','','Carrinho #'+c.id),n('p','caption','Criado em '+date(c.created)));table(selected,['Produto','Qtd.','Preço'],c.items.map(i=>[product(i.title,i.variant||i.sku,i.image),num(i.quantity),money(i.price)]));selected.append(n('div','chart-summary',c.currency==='BRL'?money(c.total):c.currency),n('p','caption',(c.notified===null?'Notificação não informada':c.notified?'Notificado pela loja':'Não notificado')+' · '+(c.stock===null?'Estoque não informado':c.stock?'Estoque disponível':'Sem estoque disponível')));if(c.url)selected.append(externalLink('Abrir checkout ↗',c.url));}
 function paint(){body.replaceChildren();table(body,['Carrinho','Criado em','Total','Notificado','Estoque'],filtered.slice(page*10,page*10+10).map(c=>[button('#'+c.id,()=>select(c),'row-link'),date(c.created),c.currency==='BRL'?money(c.total):c.currency,c.notified===null?'Não informado':c.notified?'Sim':'Não',n('span','badge '+(c.stock===false?'warn':c.stock===true?'good':''),c.stock===null?'Não informado':c.stock?'Disponível':'Sem estoque')]));pager(body,filtered.length,page,10,v=>{page=v;paint();});selected.replaceChildren(n('h2','','Detalhes do carrinho'));if(filtered.length)select(filtered[page*10]);else empty(selected,'Nenhum carrinho com esses filtros.');}paint();
 const ages=panel('Idade dos carrinhos','Apenas abandonos após a segunda etapa do checkout. Valores não representam vendas confirmadas.');const group=n('div','ns-ages');for(const [key,title]of [['day','Até 24 horas'],['three','1 a 3 dias'],['week','3 a 7 dias'],['older','Mais de 7 dias']]){const count=rows.filter(c=>bucket(c)===key).length,box=n('div');box.append(n('strong','',num(count)),n('p','caption',title));const progress=n('progress');progress.max=Math.max(1,rows.length);progress.value=count;box.append(progress);group.append(box);}ages.append(group);$('content').append(ages);});}
 function rememberControls(){const forms=[...document.querySelectorAll('#content .toolbar')],active=document.activeElement;const saved=forms.map(form=>[...form.querySelectorAll('input,select')].map(e=>({value:e.value,focused:e===active})));return ()=>{document.querySelectorAll('#content .toolbar').forEach((form,i)=>{const fields=[...form.querySelectorAll('input,select')];saved[i]?.forEach((v,j)=>{if(fields[j])fields[j].value=v.value;});if(saved[i])form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));saved[i]?.forEach((v,j)=>{if(v.focused&&fields[j])fields[j].focus({preventScroll:true});});});};}
 function render(preserve=false){const restore=preserve?rememberControls():null;document.querySelectorAll('[data-tab]').forEach(a=>{if(a.dataset.tab===tab)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});document.title=titles[tab]+' · Nuvemshop | Provou Levou';$('content').replaceChildren();document.querySelector('.date-controls').hidden=tab==='carrinhos';$('period-note').textContent=tab==='produtos'?'Vendas por data de pagamento · Brasília':tab==='estoque'?'Estoque na posição atual · ritmo de venda pelo período selecionado':tab==='carrinhos'?'Carrinhos disponíveis nos últimos 30 dias':tab==='pedidos'?'Pedidos por data de criação · Brasília':'Vendas por data de pagamento · Brasília';try{({resumo:overview,pedidos:ordersView,produtos:productsView,estoque:estoqueView,pagamentos:paymentsView,carrinhos:checkoutsView}[tab])();}catch(e){failure($('content'),e.message,()=>load());}if(restore)restore();updateStatus();}
 function updateStatus(){$('export').disabled=!resource.orders.data;const key=tab==='estoque'?'products':tab==='carrinhos'?'checkouts':'orders';$('updated').textContent=resource[key].data?'Consulta em '+date(resource[key].data.queriedAt)+' · Nuvemshop'+(resource[key].data.cache?.refreshing?' · Atualizando em segundo plano…':resource[key].data.cache?.error?' · Últimos dados salvos. '+resource[key].data.cache.error:' · Dados salvos localmente.'):'Dados ausentes não equivalem a zero.';}

 async function load(only,force=false){clearTimeout(pollTimer);let range;try{range=M.range($('start').value,$('end').value);if((new Date($('end').value)-new Date($('start').value))/86400000>365)throw Error('Selecione até 366 dias.');}catch(e){failure($('content'),e.message);return;}const run=++epoch,keys=['orders','previous','products','checkouts'].filter(k=>force!=='poll'||resource[k].data?.cache?.refreshing);const sameRange=lastRange===$('start').value+':'+$('end').value;lastRange=$('start').value+':'+$('end').value;if(!sameRange){resource.orders={};resource.previous={};nsOrderState.page=nsPayState.page=1;}$('date-label').textContent=shortDate($('start').value)+' – '+shortDate($('end').value);$('date-menu').open=false;const url=new URL(location.href);url.search=new URLSearchParams({start:$('start').value,end:$('end').value});history.replaceState(null,'',url);for(const b of $('presets').children){const v=b.dataset.period,t=M.day(new Date()),end=v==='yesterday'?M.shift(t,-1):t,start=['today','yesterday'].includes(v)?end:M.shift(t,1-Number(v));b.setAttribute('aria-pressed',String($('start').value===start&&$('end').value===end));}if(!sameRange)render();else updateStatus();await Promise.allSettled(keys.map(async k=>{let changed=false;try{const prevEnd=M.shift($('start').value,-1),prevStart=range.previous.slice(0,10);const data=await request(k==='previous'?'orders':k,{...(k==='orders'?{start:$('start').value,end:$('end').value}:k==='previous'?{start:prevStart,end:prevEnd}:{}),...(force===true?{refresh:'1'}:{})});if(run!==epoch)return;changed=resource[k].data?.queriedAt!==data.queriedAt;resource[k]={data};}catch(e){if(run!==epoch)return;if(resource[k].data){resource[k].data.cache={...resource[k].data.cache,error:e.message,refreshing:false};}else{resource[k]={error:e.message};changed=true;}}if(changed)render(sameRange);else updateStatus();}));if(run===epoch&&Object.values(resource).some(r=>r.data?.cache?.refreshing))pollTimer=setTimeout(()=>load(null,'poll'),2000);}
 for(const [value,title]of [['today','Hoje'],['yesterday','Ontem'],['7','7 dias'],['15','15 dias'],['30','30 dias']]){const b=button(title,()=>{const t=M.day(new Date());$('end').value=value==='yesterday'?M.shift(t,-1):t;$('start').value=['today','yesterday'].includes(value)?$('end').value:M.shift(t,1-Number(value));load();});b.dataset.period=value;$('presets').append(b);}
 $('date-form').addEventListener('submit',e=>{e.preventDefault();load();});$('refresh').addEventListener('click',()=>load(null,true));$('close-detail').addEventListener('click',()=>$('detail').close());window.addEventListener('hashchange',()=>{tab=titles[location.hash.slice(1)]?location.hash.slice(1):'resumo';render();});
 $('export').addEventListener('click',()=>{const data=resource.orders.data;if(!data)return;const rows=[['Pedido','Criado em','Pago em','Situação','Pagamento','Total BRL'],...data.orders.filter(inCreated).map(o=>[o.number,o.created,o.paidAt||'',label(o.status),label(o.payment),o.currency==='BRL'&&o.total!==null?(o.total/100).toFixed(2):''])];const csv='\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=n('a');a.href=url;a.download='nuvemshop-pedidos-'+$('start').value+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 try{client=window.supabase.createClient(window.SUPABASE_CONFIG.URL,window.SUPABASE_CONFIG.KEY);const {data:{session}}=await client.auth.getSession();if(!session){location.href='login.html';return;}$('logout').addEventListener('click',async()=>{await client.auth.signOut();location.href='login.html';});tab=titles[location.hash.slice(1)]?location.hash.slice(1):'resumo';await load();setInterval(()=>{if(!document.hidden&&!document.querySelector('input:focus,select:focus,textarea:focus'))load();},60000);}catch(e){failure($('content'),'Não foi possível iniciar o painel. '+e.message);}
});
